### ISSUE TITLE
Delete functionality

### ISSUE THREAD

**Issue by ambrussimon** [scitran/core#1012]
* Allow deletion of individual files, as well as of Projects, Sessions, and Acquisitions, and Analyses
* Project deletion requires Admin privileges, all other deletes require RW privileges
* Project and Session deletes include deleting of all contained Analyses
* Delete confirmation dialog offers option to "purge immediately" (meaning within 24 hours); Otherwise, deleted data will be purged after 90 days.
* Until purged, data can be restored by Flywheel support only
* Files and acquisitions, which are referenced by Analyses, may not be deleted by the user; appropriate UI/CLI/SDK warning dialogs needed
* Remove deleted items from Elastic (search)
* Tag all currently hidden files and containers as "hidden" and do not mark them as deleted.  (We will inform customers that hidden files are being restored, but are tagged as "hidden" so they can search on them and delete if wanted.)

Remaining questions:
* Do we remove jobs that only reference deleted containers?
* Do we allow deleting utility gear input files? Breaking provenance, but freeing space.

**Comment by ryansanford** [comment]
@ambrussimon Can/will you be providing utility script/endpoint that can be used for the file purge and "restore by support" aspects? I assume my portion is to create a cron job for the purging, and convenience commands for purging and restoring in both DEV and PROD environments.
