### ISSUE TITLE
Allow Filenames with slashes

### ISSUE THREAD

**Issue by hkethi002** [scitran/core#1071]
Currently slashes are removed on file upload, we should allow for filenames with slashes, and simply allow it to be a part of the download path.

**Comment by kofalt** [comment]
I believe this would break our client, which assumes a slash is a directory separator. Are you sure we cannot continue stripping them? Slashes are not a part of a healthy filename.

**Comment by nagem** [comment]
There were requests to see what changes would be required to store slashes as part of a Mongo object's filename so it could be maintained on download and clients could display the additional path information. This PR is currently a holding ground for @hkethi002 exploratory work.

**Comment by kofalt** [comment]
Ah, I see you are referencing #1077 :+1:

**Comment by nagem** [comment]
Ah yes didn't realize we were in the issue not the PR.
