### ISSUE TITLE
Analysis jobs do not transition to complete state when using completion tickets

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#1084]
Non-analysis jobs complete fine. Only analysis jobs are impacted.

**Comment by nagem** [comment]
Is this with a new engine using the new interface for uploading the results?

**Comment by kofalt** [comment]
Will wait on successful completion of #1079.

**Comment by kofalt** [comment]
Updated ticket title to clarify that this only occurs when using the new, optional job completion tickets. For now, simply do not use them.
