### ISSUE TITLE
Prevent mongo conflating data & syntax

### ISSUE THREAD

**Issue by kofalt** [scitran/core#134]
One of the most critical features of database usage is a clear separation of input data and query syntax. In the SQL world, this mandates the use of [parametrized queries](https://www.owasp.org/index.php/Query_Parameterization_Cheat_Sheet). NoSQL solutions have similar but different restrictions: in Rethink, the attack surface is [very limited](https://github.com/rethinkdb/rethinkdb/issues/3438) due to its clear separation in both the driver API and the wire protocol. 

In Mongo, things are less clear - JSON syntax conflates with JSON data, with no separation between the two. This is incredibly problematic when one desires to... store JSON, in the JSON store :)

My _current_ understanding is that there are only two entry points for Mongo syntax: keys beginning in `$` or containing `.`. These can occur anywhere in the query, and can cause insecure or failed queries.

Some docs about this:
- https://docs.mongodb.org/manual/core/document/#dot-notation
- https://docs.mongodb.org/manual/faq/developers/#faq-dollar-sign-escaping

Because we are using JSON schemas for a large portion of our input data, the majority by volume of our endpoints won't see this problem. This applies to any endpoints not covered by schemas, and anywhere unstructured data is allowed (for example, container metadata).

What's very concerning to me is that sanitization seems to be ad-hoc and in-house to any given codebase, rather than internal to the database protocol or driver API. Further, Mongo seems to advocate _swapping unicode code points_ for equivalently-rendered characters, in lieu of a proper escape sequence.

Many thanks to @aaltepet, who has more experience in mongo and offered this code sample:

``` python
def mongo_escape(fname):
    """
    Sanitize MongoDB keys by replacing reserved chars with full-width 
    equivalents.

    MongoDB doesn't support using '.' and '$' as document keys, and suggests
    converting the chars to their unicode full-width equivalents.
    cf. http://docs.mongodb.org/manual/faq/developers/#faq-dollar-sign-escaping
    """
    return fname.replace('.', '\uFF0E').replace('$', '\uFF04')


def mongo_unescape(fname):
    """
    Desanities MongoDB keys by replacing full-width chars with normal
    ascii equivalents

    MongoDB doesn't support using '.' and '$' as document keys, and suggests
    converting the chars to their unicode full-width equivalents.
    cf. http://docs.mongodb.org/manual/faq/developers/#faq-dollar-sign-escaping
    """
    return fname.replace('\uFF0E', '.').replace('\uFF04', '$')
```

Note that this means data stored in the database is **no longer valid** - it's a translation that can't be sent anywhere else, so it has to be unconverted back on its way out.

Contrast @rentzso's [utility function](https://github.com/scitran/api/blob/df27702431f510ba4392198dd24d442f617dd482/api/util.py#L32-L36), which takes a map, rather than a single key:

``` python
def mongo_dict(d):
    def _mongo_list(d, pk=''):
        pk = pk and pk + '.'
        return sum([_mongo_list(v, pk+k) if isinstance(v, dict) else [(pk+k, v)] for k, v in d.iteritems()], [])
    return dict(_mongo_list(d))
```

The focus of this ticket, then, is threefold:
- [ ] Identify the most-robust, least-custom method for sanitizing and transport
- [ ] Ensure said method is universally applied
- [ ] Put measures / tooling in place to prevent diverging away from 100% coverage.

For the first item, my off-the-cuff feeling is that I like @rentzso's approach of sanitizing a map all at once; maybe we continue with something like that, or use unicode-swapping to avoid collisions. Maybe this rolls into the same logic we use for escaping & unescaping the mongo ID not-quite-strings.

Of course, this logic shouldn't be within 30 feet of an individual CRUD API project; I had a look around expecting an implementation in pymongo or similar and came up empty. A library option would be ideal. 

For the second action item: Also discussed with @aaltepet was the possibility of wrapping or augmenting pymongo. Presumably the best approach might be a `raw(map)` func that is always used when passing any map to mongo that isn't expected to contain syntax. An `unraw(map)` will be necessary on each query result if we do unicode-swapping.

For the third action item: open to ideas! In other languages I'd have several tooling suggestions; maybe pylint or similar can help us here.

**Comment by gsfr** [comment]
Excellent analysis! Thank you, @kofalt. Looking forward to a PR.

**Comment by ryansanford** [comment]
What's the current use-case for needing keys containing '.' and '$' ? If this is 3rd party data that we are simply stewarding, and don't require querying or updating pieces, we should consider storing as a blob in the DB.

If we really need to persist it as a json document in mongo, and code on the app side of pymongo is required, I would prefer wrapping pymongo.

Curious if this son_manipulator class is applicible to the concern? Maybe it doesn't cover queries?https://api.mongodb.org/python/current/api/pymongo/son_manipulator.html

Also if we are transforming keys, we need to understand the impact to elasticsearch use-cases.

**Comment by kofalt** [comment]
Basically this part of the ticket:

> This applies to any endpoints not covered by schemas, and anywhere unstructured data is allowed (for example, container metadata).

The specific incident we ran into was storing dicom metadata that happened to include `.` characters in the keys. The container metadata field is, by design, completely unstructured and (should be) allowed to store largely-arbitrary key-value content.

> Curious if this son_manipulator class is applicible to the concern?

I'm not sure. I really don't want to be mucking about with [SON stuff](http://api.mongodb.org/python/current/api/bson/son.html) if we can help it. That said, it mentions `pymongo.database.Database.add_son_manipulator` which implies we could do some translation transparently, which would be nice.

> I would prefer wrapping pymongo

Me too, I think, except that due to the nature of mongo queries it's not possible to tell after-the-fact what's data and what's syntax, so I'm not sure of the best approach. And if there is a good approach, I don't want to write it; I want someone else to have done so in a library... Maybe a discussion on the pymongo tracker would be productive.

**Comment by ryansanford** [comment]
@kofalt 
Can you post a sample of the offending dicom metadata json?

**Comment by kofalt** [comment]
@ryansanford Excellent question!

```json
"metadata" : {
    "LastScanLoc" : 36.0000000000000000,
    "FlipAngle" : 90.0000000000000000,
    "DB/dtPeakRateOfChangeOfGradientField" : 0.0000000000000000,

    "User_fill_map_MSW" : 0,

    "Horiz_FrameOfRef_" : 322.5000000000000000,
    "PhaseContrastFlowAxis" : 0,
    "Slop_int_6___Slop_int_9" : [ 
        0, 
        1, 
        0, 
        0
    ],

    "User_fill_map_LSW" : 0,
}
```

This is a liberally-truncated example from our sample data set after classification.
The full set can be viewed [here](https://gist.github.com/kofalt/b91df670f9bbcd005448).

 @rentzso added a [workaround](https://github.com/scitran/api/blob/d0de3624ef660ec93002849a5d82f7c56733664d/api/util.py#L31-L43) to this issue that swaps `.`s for `_`s, so I cannot state with certainty that these keys originally contained `.`s. Right now, the workaround does **not** resolve key collisions!

**Comment by ryansanford** [comment]
I learned from @kofalt that the above sample had already been sanitized.

@gsfr 
I think changing the API in reaction to this pain-point (metadata gear) is a mistake. Once we persist transposed data in the database, we'll need to deal with the repercussions for a long time. If the direction changes in the future, updating database values in the field at sites can be a labor intensive endeavor.

For bali, I would much rather us change the gear to sanitize the json keys. This gives us time to make sure we appreciate the impact of sanitizing in the API.

The strings in the sample are not canonical, the group,element codes are. We should not expect to use those keys in a predictable way down the line without an actual dicom group,element to string dictionary that is enforced. Ideally, we would store the dicom group,element in the db so it could stand on its own without the dictionary.

**Comment by kofalt** [comment]
Proposal: for the bali release, we keep what we have with the modification of adopting @aaltepet's two-directional translation for metadata. This would keep everything the same with the exception that our keys no longer collide and can be retrieved in their original (post-gear) form.

Keeping dicom metadata, and translations thereof, in a robust fashion, is a pretty large task, and I don't think we're there yet. But we can deliver a non-destructive variant of the current behaviour without too much trouble.

**Comment by gsfr** [comment]
> The container metadata field is, by design, completely unstructured and (should be) allowed to store largely-arbitrary key-value content.

Indexable, queryable content, that is.

**Comment by ryansanford** [comment]
Spoke with @gsfr and @kofalt 
Conclusion is we stick with status quo for bali.01

Bali.02 we consider
1. add schema validation to reject metadata with '.' for '$' in key names.
2. Change classifier gear to sanitize it's metadata
3. Change gear spec to require metadata not have '.' or '$' in key names of output.

Post bali.02
1. Change classifier gear to store metadata keys as dicom group,element, implementing dictionary for API and/or frontend to map those to text strings.
2. Update gear spec to recommend 3rd party gear keys be as cannonical as possible, and provide guidance how dicom metadata should be key'd to leverage our dictionary and search capabilities.
3. Rerun classifier gear to make suer all dicom metadata now fits our new guidelines.

The longer it takes us to get to that last item, the more data will be in the field that will need to be re-processed.
