### ISSUE TITLE
Type conflating with MIME type

### ISSUE THREAD

**Issue by kofalt** [scitran/core#153]
Ref #151 about `type: "gif"` being returned on a container's file:

1. `gif` isn't a mime type (contrast `image/gif`)
1. This field is also used for scientific data types (`dicom`)

This is troublesome when trying to make UI-relevant decisions (deciding if a viewer icon should be visible, which viewer to launch, etc).

My proposal:

1. The `type` field is only used for scientific data - so, `dicom` and similar. Blank (empty string) if there isn't a scientific data type flagged on this file.
1. A new `mime` field is sent on all files (data and attachments) that has a best-guess mimetype on it. Defaults to `application/octet-stream`.

Thoughts? @mrDarcyMurphy @dpuccetti-flywheel

**Comment by gsfr** [comment]
In various data model-related discussions, the team had previously deemed the mime type on files as superfluous. The API finally [caught up](https://github.com/scitran/api/pull/140) this week.

Per our [current data model](https://github.com/scitran/api/wiki/Data-Model#file-subdocument-only), `type` is the human-interpretable file type, such as dicom, image, or document. The mime type is not part of the model, but still provided in the HTTP `Content-Type` header for downloads.

If there is a genuine need for the API to supply the mime type of each file, I would be open to doing so post-bali, as part of the [new data model](https://github.com/scitran/api/wiki/Data-Model,-v2#file-subdocument-only). Note, though, that the API's potential functionality would be limited to *guessing* the mime type based on filename extension, not on actual file content. I would be concerned about supplying such *guesses* from what is intended to be an authoritative data source.

Could the UI alternatively take on the guess work?

@elisapoquette: Determining file types will likely need to become part of file uploads, possibly by prompting the user.

**Comment by mrDarcyMurphy** [comment]
The UI is already using a simple regex to grab the file extension to see if it's viewable or not, and how. If that's really the best way then I guess we'll stick with it.

I was hoping the API would be smarter about determining the mime-type other than sniffing the file extension. If not, then maybe the best middle-ground would be to have the API return the extension as an attribute. That'd save some code and processing time on the UI.

```
{
  created: "2016-02-04T01:24:43.498000+00:00"
  hash: "v0-sha384-6d256b480d71816cb822f721e9cb36d28e7d0fd2b1005ef74ee2c89ea75dc5e9a46c3dc950659eb0a2e689fb02422bfd"
  modified: "2016-02-04T01:24:43.498000+00:00"
  name: "cookie.gif"
  size: 466272
  ext: "gif"
}
```

Lastly, Rule # 1 of UX is "Don't make me think." Putting the responsibility on the user to figure out what type of file they're uploading would violate that, along with being tedious and frustrating. It'd be a solid foot-gun too, as people are likely to pick the wrong file type.

**Comment by mrDarcyMurphy** [comment]
One additional complication is nifti files. When they're generated they're served like so:

```
{
  hash: "v0-sha384-c19d53315db25d1678460697767e3e0c5416bfc2cc9fa0915bf15c829877133b900b9972624fde5d8c4568a85e3a1215"
  name: "8892_14_1_dti_nifti.nii.gz"
  size: 34090235
  type: "nifti"
}
```

However, if I were to download that nifti and reupload it to a different spot, it's served like so:

```
{
  created: "2016-02-08T16:44:17.213000+00:00"
  hash: "v0-sha384-874966c33a76ca5aeab4654d30015841965c4f35acd0fa45b9d2686c4d4b876e5578a5f81fc65812e750842b47b6e7e9"
  modified: "2016-02-08T16:44:17.213000+00:00"
  name: "8892_1_1_localizer_nifti.nii.gz"
  size: 8738921
}
```

Since the file extension is `gz` the UI has no way of knowing which type of file is actually in there. It could be assumed that `.nii.gz` is a nifti, and I plan on checking for that for now, but it's a guessing game and that seems wrong.

**Comment by gsfr** [comment]
By design, the API does not and will not interpret the files that it is hosting. We are data type and format agnostic. Data sources, such as reapers, gears, and UI, must supply all relevant file metadata.

If it makes anyone's life easier, I'd be happy to add a `mimetype` field to each file, even to guess it using a [standard library](https://docs.python.org/2/library/mimetypes.html) if it's not supplied, but I really don't see us adding deep file inspection and knowledge of every possible file type ever invented.

**Comment by mrDarcyMurphy** [comment]
It's reasonable for the API to be agnostic, but it doesn't have to be ignorant. Both the API and the UI need to know what type of files they're working with in order to present them properly to users.

Judging by the standard library's docs, the uploaded nifti example would end up being considered a gzip file. `mimetypes.encodings_map['.gz'] => 'gzip'`. It's not wrong, but for our use case it's not exactly right either.

Perhaps we aim for a middle ground where the API and the UI make a best guess, and we allow the user to change the file type after upload. I still recommend against forcing the operation during upload, but a "get out of jail free" card afterwards would be alright.

For (a very rough) example: 

![screen shot 2016-02-09 at 9 53 15 am](https://cloud.githubusercontent.com/assets/21331/12921446/fc8a17b6-cf12-11e5-8848-a17d7802ba64.png)

Clicking Edit could switch the table row, like we do with permissions, so that the user can change the file type and potentially the file name.

Your thoughts?

**Comment by kofalt** [comment]
Agreed on agnostic != ignorant, that's a good way to put it.

Even from a distance I'm not entirely comfortable with the amount of logic that's ending up in the frontend and would be happier if the API can shoulder it as much as possible. The server making a best-effort attempt to help here makes sense. The python extension-guess @gsfr linked would be sufficient, but AFAIK, the most correct option to do this is the standard *nix tool:

```bash
$ file --brief --mime-type stuff 
text/x-shellscript

$ file --brief --mime-type latest.jpg
image/jpeg

$ mv latest.jpg wat.txt

$ file --brief --mime-type wat.txt 
image/jpeg

# Does not take longer on large files; this one is 2 GB
$ time file --brief --mime-type large.tar 
application/x-tar
real	0m0.003s
```

The `file` command does not read the entire file, not the filename, instead doing a variety of intelligent (and configurable) checks which complete quickly. This is ideal, since extensions aren't real.

Whichever method is used, I most strongly would assert that the API should calculate once and store, rather than re-calculating on request. Our own scientific heuristics belong solely in the `type` field - if the identifying methodology thinks it's `application/octet-stream`, we store that unmodified in the `mime` field where it belongs. The UI then has to look at both to make a decision on what to do; first checking the `type` field then, if empty (?) using the `mime` field.

Proposal in action (assuming `file` is used):

file | type | mime
----|------|----
doc.pdf | | application/pdf
image.png |  | image/jpeg
example.nii.gz | nifti | application/gzip
example.nii | nifti | application/octet-stream
example.dcm | dicom | application/dicom

Download API calls would use the stored `mime` field in headers for obvious reasons.
Thoughts?

I have less an opinion about editing after the fact - @elisapoquette, what do you think of allowing the user to specify (after a file is uploaded) what sort of file it is? If that's an important feature, I don't see any reason not to allow users with write access to make that change. Validating what they sent first, of course...

**Comment by gsfr** [comment]
Well, when we are looking at a gzipped or native NIFTI file, the critical part for our system's functionality is `type="nifti"` and `measurements=["functional"]`, for instance. Similarly for a zip of DICOMs. That's what the viewers and gears need to know. The mime type, `application/gzip`, `application/zip`, or `application/octet-stream` is both easy to determine automatically and also much less important for us. No further discussion is needed on this field. We will add it to the data model, and if it's not supplied by the data source, the api will make an educated guess.

Back to the meat: `type` and `measurements` are critical for our system's functionality.

Given the lack of an algorithmic solution, letting the user set those fields on file upload as well as allowing later modification seems obvious to me.

To @mrDarcyMurphy's point about the user messing up: Sure, that will doubtlessly happen. But they will figure it out when their gears and viewers fail, provided we give them a rich UI and intelligible feedback.

@elisapoquette: How does that all look from your UX point of view?

**Comment by elisapoquette** [comment]
Let's take the UI stuff offline. I will make an Aha! ticket for these features and we can go through a design review.

**Comment by elisapoquette** [comment]
Also, @mrDarcyMurphy proposal is very much inline with what I would recommend

**Comment by kofalt** [comment]
Let's take the "type + measurement" modification stuff to another ticket then, as this ticket is only about resolving the conflation between `type` and mime. I think I heard agreement on my proposal above; let's go with that. Storing the result of any heuristics leave the door open for user modification after-the-fact.

**Comment by mrDarcyMurphy** [comment]
@kofalt Does that mean the API would return something like this for a nifti file? If so, it'd work well and should eliminate guess work.

```
{
  name: "example.nii.gz",
  type: "nifti",
  mime: "application/gzip"
}
```

**Comment by kofalt** [comment]
Yup!

**Comment by gsfr** [comment]
And how would the API know that this file is of `type: "nifti"`? That's the whole point of this discussion.

**Comment by kofalt** [comment]
Not so:

> Per our current data model, type is the human-interpretable file type, such as dicom, image, or document.

My proposal is to do only a subset of the current behaviour - specifically, to only store one of those three examples - in the `type` field. And to store a more mime-standard string than `gif` (ref #151) in a separate `mime` field.

**Comment by mrDarcyMurphy** [comment]
:+1:
