### ISSUE TITLE
harmonize group schema with other container schemas

### ISSUE THREAD

**Issue by rentzso** [scitran/core#156]
this changes will be  applied
`group._id` becomes `group.uid`
add group._id as ObjectId
`group.roles` becomes `group.permissions`

**Note:** coordinate with ui team

**Comment by kofalt** [comment]
I'm not sure I understand the first part of the summary.

Is `group._id` being duplicated to `group.uid`?
Will `group.uid` it be a different type than `group._id`?

**Comment by rentzso** [comment]
`group.uid` will be the human-readable unique id of the group.
`group._id` will be an ObjectId as in projects, sessions and acquisitions.

This change will allow a lot of code removal, as there is no need of custom logic on the level to parse the `_id` as it will be an ObjectId for every level.

An example could be these two lines:
https://github.com/scitran/api/commit/122b0eb4f3584d9dbe68dcf4ae99bf315b063abd

Instead of 
```
if cont_name in ['sessions', 'acquisitions']:
     payload[parent_id_property] = bson.ObjectId(payload[parent_id_property])
```
we would have just 
```
payload[parent_id_property] = bson.ObjectId(payload[parent_id_property])
```
as all the `_id` fields (and their references) will need to be converted to ObjectIds.

**Comment by nagem** [comment]
Ideas separated into #662, #814, #848 - closing
