### ISSUE TITLE
Upload unification & upgrades

### ISSUE THREAD

**Issue by gsfr** [scitran/core#159]
Edited by @kofalt - itemized list:
1. [x] Lay initial groundwork for upload unification. (@kofalt)
2. [x] EnginePlacer is written but needs to be rigged up and connected to the endpoint. (@nagem)
3. [x] LabelPlacer and (new) UidPlacer should replace most logic currently in upload.reaper and upload.uploader. (@rentzso)
4. [x] After that is complete, consider unifying the LabelPlacer & UidPlacer. (@gsfr)
5. [x] Generate closures for on-the-fly processing; performance optimization. (@kofalt)
6. [x]  Once all the above is complete, consider input schema unification(@gsfr)
7. [x]  Once all the above is complete, consider Placer naming changes (@kofalt)

**Comment by kofalt** [comment]
Attached: some workshop notes from a discussion last week.
Might not make a ton of sense if you weren't there, sorry :)

```
Use cases
- Engine
- Connector / Reaper
- User
- User with a set of dicoms

Features
                                                | Engine | Reaper | User | User-dicom
Upload (may) target a specific container        | Y                  Y        Y
Upload to different parts of the hierarchy      | Y         Y                  
Create hierarchy on demand                      |           Y                  
Send metadata with each file                    | Y         Y        Y        Y
Take a set of files (dicom) and produce zipfile |                             Y

Proposal
- Multi-file
- Unify the metadata
- Based on auth, we decide if you're allowed
	- If you're not a reaper, reject if hierarchy isn't there
	- 

/api/containers/3/files <-- endpoint

Ordered proposal:
3. Multi-file (multipart form uploads)
4. Optionally consumes metadata (required in the reaper case)

Later:
1. Targetted
2. General   /api/upload

Code sample:
# Updates a single container
# Moving the file
# Update / create the db
class PreparedFileUpdate(object):
​
    def __init__(self, cont_name):
        pass
​
    def add_query_condition(self, condition):
        pass
​
    def add_update_sections(self, update_sections):
        pass
​
    def new_files(self, files, force=False):
        pass
​
    def exec_update(self):
        pass
​
    def check_target(self):
        pass
```

**Comment by kofalt** [comment]
It's my understanding that the `UIDPlacer` and `LabelPlacer` are complete, ticking that box. The code basically is unified right now via subclassing, so ticking that box. We punted on closure generation, and naming turned out to be fine, so ticking those boxes. Editing final placer box to be unassigned. Moving ticket back to @gsfr for prioritization of the last item :)

**Comment by gsfr** [comment]
Let's talk about schema unification at standup tomorrow. I'd also love to finally get rid of the schema composition loopback shenanigans.

**Comment by nagem** [comment]
While working on #360, I noticed that `upload.reaper` is still there. Has the reaper been updated to use either the label or UID endpoint, and if so, can this be removed? @gsfr @rentzso

**Comment by gsfr** [comment]
Yes, we only use `/upload/uid` and `/upload/label`.

**Comment by kofalt** [comment]
Can we close this given that @nagem is working on jinja stuff, which will probably handle dedup?

**Comment by gsfr** [comment]
Let's reserve @nagem the gratification of closing this from her anticipated jinja PR.

**Comment by nagem** [comment]
How do we feel about "input schema unification" after #406?

**Comment by gsfr** [comment]
Keeping this open per offline discussion with @nagem.

**Comment by nagem** [comment]
Input schema has been considered, keeping separate is the best option available.
