### ISSUE TITLE
Surprising 500 when creating acquisition

### ISSUE THREAD

**Issue by kofalt** [scitran/core#173]
`http --verify=no POST https://localhost:8443/api/acquisitions label=example 'User-Agent:SciTran Drone Script' X-SciTran-Auth:change-me`
```json
{
    "message": "'NoneType' object has no attribute '__getitem__'", 
    "status_code": 500
}
```
```
File "webapp2.py", line 570, in dispatch
  return method(*args, **kwargs)
File "./api/handlers/containerhandler.py", line 222, in post
  payload[parent_id_property] = parent_container['_id']

TypeError: 'NoneType' object has no attribute '__getitem__'
```

This example tried to create an acquisition with the only [required schema field](https://github.com/scitran/core/blob/bbb45fe09164bde8d74c420ef97f11bf2bbba331/api/schemas/input/acquisition.json#L18): `label`. It looks like a crash caused by the inability to find a parent container.

I would have expect something other than a 500. Presumably, `session` is also required. I'm not sure if this needs a schema change or just more error handling in containerhandler.

**Comment by kofalt** [comment]
Substituting `acquisitions` for `sessions` or `projects` also works.

**Comment by gsfr** [comment]
`/acquisitions` should not exist at all, and `/sessions` should be restricted to `GET`.

I also ran into this issue, or rather a very related one, this weekend.

I'm expecting the following endpoints:
```
POST /groups/<gid>/projects {"label": <project label>}
```
```
POST /projects/<pid>/sessions {"label": <session label>}
```
```
POST /sessions/<sid>/acquisitions {"label": <acq label>}
```
All should return the newly created or existing `_id`.

**Comment by kofalt** [comment]
> /acquisitions should not exist at all

I'm not sure I agree. If an acquisition has only one session (mandated by our model), why make it harder to access or modify? I don't get it.

> /sessions should be restricted to GET

I like this idea better... but disagree for the same reason. How about [PUT, GET] ?

**Comment by gsfr** [comment]
I'm sorry, I wasn't very clear here and also wrong. The 3 `POST`s mentioned above are actually all different. Here are the correct ones.

```
POST /projects {"group": <gid>, "label": <project label>}
```

```
POST /sessions {"project": <pid>, "label": <session label>}
```

```
POST /acquisitions {"session": <sid>, "label": <acq label>}
```

---

>> /acquisitions should not exist at all

> I'm not sure I agree. If an acquisition has only one session (mandated by our model), why make it harder to access or modify? I don't get it.

What I meant to say here is that there should be no way to retrieve all acquisitions that a user has access to (`GET /acquisitions`), which has the potential to be pretty much the entire database.

>> /sessions should be restricted to GET

> I like this idea better... but disagree for the same reason. How about [PUT, GET] ?

Given the corrected endpoints above, this makes no sense anymore. But a `PUT` verb on a list endpoint also makes no sense.

**Comment by kofalt** [comment]
Ah, that all makes sense then. Carry on!
