### ISSUE TITLE
deadlocks with pymongo possible

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#180]
Deadlock can happen because the global "db" variable is used to connect to the DB via the api.wsgi entrypoint before uwsgi forks the process. 

I initially looked into this because of this message in the uwsgi log:
```
uwsgi_1          | 2016-03-03 15:38:05      scitran.api                config.py   121:DEBU Refreshing configuration from database
uwsgi_1          | /usr/local/lib/python2.7/dist-packages/pymongo/topology.py:74: UserWarning: MongoClient opened before fork. Create MongoClient with connect=False, or create client after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#using-pymongo-with-multiprocessing>
uwsgi_1          |   "MongoClient opened before fork. Create MongoClient "
```

@rentzso and @gsfr 
Besides avoiding the config.get_item() call in this case, can a unit test be created to expose similar regressions in the future? Maybe api.app_factory() could be moved to its own file to reduce the surface area of global includes?

Deadlock Background here:
http://api.mongodb.org/python/current/faq.html#using-pymongo-with-multiprocessing

Offending line:
https://github.com/scitran/core/blob/master/api/handlers/searchhandler.py#L10

Stack trace:
uwsgi_1          | Traceback (most recent call last):
uwsgi_1          |   File "bin/api.wsgi", line 3, in <module>
uwsgi_1          |     from api import api
uwsgi_1          |   File "./api/api.py", line 19, in <module>
uwsgi_1          |     from handlers import searchhandler
uwsgi_1          |   File "./api/handlers/searchhandler.py", line 10, in <module>
uwsgi_1          |     es_client = elasticsearch.Elasticsearch([config.get_item('persistent', 'elasticsearch_host')])
uwsgi_1          |   File "./api/config.py", line 139, in get_item

**Comment by kofalt** [comment]
Nice find. I suspect that #172 would be solved by solving this issue.

**Comment by rentzso** [comment]
It looks like an issue related to the API "global" behavior, so integration testing should be the right way of testing it.
@ryansanford could you attach the full uwsgi logs? I don't understand if the Stack Trace is before or after the warning

@gsfr what are the reasons to persist the config?

**Comment by ryansanford** [comment]
@rentzso 

To capture the stack trace, I introduced an exception into config.get_item(). I tried to just print the stack trace, but as you can see from the uwsgi output, I forgot to import traceback, which in the end, got me what I wanted, the stack trace from the api.wsgi entrypoint.

config.api change to force exception:
```
def get_item(outer, inner):
    try:
        raise Exception()
    except Exception as error:
        log.debug(traceback.format_exc())
    return get_config()[outer][inner]

```


uwsgi output:
```
uwsgi_1          | [uWSGI] getting INI configuration from config/uwsgi-config.ini
uwsgi_1          | *** Starting uWSGI 2.0.11 (64bit) on [Thu Mar  3 17:40:07 2016] ***
uwsgi_1          | compiled with version: 4.8.4 on 03 March 2016 13:08:15
uwsgi_1          | os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
uwsgi_1          | nodename: a95e17acb465
uwsgi_1          | machine: x86_64
uwsgi_1          | clock source: unix
uwsgi_1          | detected number of CPU cores: 2
uwsgi_1          | current working directory: /var/scitran
uwsgi_1          | detected binary path: /usr/local/bin/uwsgi
uwsgi_1          | !!! no internal routing support, rebuild with pcre support !!!
uwsgi_1          | chdir() to code/api
uwsgi_1          | your processes number limit is 524288
uwsgi_1          | your memory page size is 4096 bytes
uwsgi_1          | detected max file descriptor number: 524288
uwsgi_1          | lock engine: pthread robust mutexes
uwsgi_1          | thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi_1          | uwsgi socket 0 bound to TCP6 address [::]:9000 fd 3
uwsgi_1          | Python version: 2.7.6 (default, Jun 22 2015, 18:01:27)  [GCC 4.8.2]
uwsgi_1          | Python main interpreter initialized at 0x2403db0
uwsgi_1          | python threads support enabled
uwsgi_1          | your server socket listen backlog is limited to 100 connections
uwsgi_1          | your mercy for graceful operations on workers is 60 seconds
uwsgi_1          | mapped 415360 bytes (405 KB) for 8 cores
uwsgi_1          | *** Operational MODE: preforking+threaded ***
uwsgi_1          | added code/data to pythonpath.
uwsgi_1          | 2016-03-03 17:40:08      scitran.api                config.py    85:DEBU Database(MongoClient(host=['scitran-mongo:27017'], document_class=dict, tz_aware=False, connect=False, replicaset='elasticflywheel', connecttimeoutms='300000', j=True, serverselectiontimeoutms='300000'), u'scitran')
uwsgi_1          | Traceback (most recent call last):
uwsgi_1          |   File "bin/api.wsgi", line 3, in <module>
uwsgi_1          |     from api import api
uwsgi_1          |   File "./api/api.py", line 19, in <module>
uwsgi_1          |     from handlers import searchhandler
uwsgi_1          |   File "./api/handlers/searchhandler.py", line 10, in <module>
uwsgi_1          |     es_client = elasticsearch.Elasticsearch([config.get_item('persistent', 'elasticsearch_host')])
uwsgi_1          |   File "./api/config.py", line 139, in get_item
uwsgi_1          |     log.debug(traceback.format_exc())
uwsgi_1          | NameError: global name 'traceback' is not defined
```
