### ISSUE TITLE
Update JSON schema to match Data Model v2

### ISSUE THREAD

**Issue by nagem** [scitran/core#189]
https://github.com/scitran/core/wiki/Data-Model,-v2

Changes:
- [x] Rename all `metadata` fields to `info`
  - [x] Rename `info` variable in `placer.py` and `upload.py` to file_attrs to avoid confusion between field and variable. `metadata` now only refers to data sent by client as part of upload process, `info` refers to the file object field representing a key-value store, `file_attrs` refers to the python variable that passes file object attributes persisted to the DB
- [x] Remove acquisition `instrument` and `measurement` fields
- [x]  `file.instrument` becomes `file.modality`
- [x] Ensure all italicized fields are returned in all GET requests (list and singular)
- [x] Return entire permissions list for admin GET requests that return lists

**Comment by ryansanford** [comment]
@nagem 
Does this encompass the DB schema update work? If not, is there a separate existing ticket to track that? Thanks.

**Comment by nagem** [comment]
@ryansanford IMO it does, but we could split it out into a generic schema upgrade framework ticket if that would be better for visibility.

**Comment by elisapoquette** [comment]
@nagem can you notify me/Dan when this is complete so we can switch how information icons are viewed on UI?

**Comment by nagem** [comment]
There is a PR open and finished that needs to be rebased but this change is breaking so work can begin on https://github.com/flywheel-io/frontend/issues/230 targeting [this branch](https://github.com/scitran/core/tree/data-model-v2).
