### ISSUE TITLE
Unable To Download Acquisition Data

### ISSUE THREAD

**Issue by dpuccetti** [scitran/core#197]
Attempting to download acquisition data is currently returning a 500 error response:

{"status_code": 500, "message": "payload_from_schema_file() takes exactly 1 argument (2 given)"}

Request URL: https://dev.flywheel.io/api/download
Method: POST
Payload: {"optional":true,"nodes":[{"level":"acquisition","_id":"56b3586772ff76421fbca74b"}]}

To reproduce: navigate to dev.flywheel.io, select any session, check any of the boxes next to the acquisitions and then under Actions select "Download Acquisitions".

**Comment by kofalt** [comment]
I believe this to be fixed on master. Close or re-comment as desired :smile:

**Comment by rentzso** [comment]
@dpuccetti could you check if this is still an issue?

**Comment by dpuccetti** [comment]
Looks good to me
