### ISSUE TITLE
File Input Schema - 'null' type for files

### ISSUE THREAD

**Issue by lmperry** [scitran/core#210]
Currently when uploading files at the acquisition level, files that do not have a type set are rejected and the `folder_reaper` is halted. 

The current "fix", in place on the deployed instances, is for:
 `   "type":           { "type": "string" },`

to become:

`    "type":           { "type": ["string", "null"] },`

https://github.com/scitran/core/blob/master/api/schemas/input/file.json#L6

Other thoughts on how to handle this?

**Comment by kofalt** [comment]
Tagging @rentzso and @gsfr for comment on this.

**Comment by gsfr** [comment]
We may simply not always know the type. `null` seems fine. UI needs to handle appropriately, of course.

**Comment by nagem** [comment]
@gsfr this should be fixed with https://github.com/scitran/reaper/commit/29db44cec54f26a4613b62ce2a23c59a387ed0a7, correct?

Closing this ticket if so.

**Comment by gsfr** [comment]
Yes, closing.

We still need a larger discussion on how we want our schemas to behave. To me, it seems annoying that I'm not allowed to send null for a non-required field. More importantly, though, we need our schemas to behave consistently and predictably across the entire app.
