### ISSUE TITLE
FolderPlacer

### ISSUE THREAD

**Issue by kofalt** [scitran/core#215]
There's a [more-uploads branch](https://github.com/scitran/core/compare/more-uploads) with a dry-coded FolderPlacer prototype from pair programming with @rentzso. Sounds like some more changes will also be included, from an email with @gsfr and @nagem:

> We should always do fuzzy matching on group names. Humans are terrible at spelling.
> We should always do case-insensitive, non-fuzzy matching on project labels.

**Comment by nagem** [comment]
Closed via #232.
