### ISSUE TITLE
bin/database.py exception log is invalid

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#219]
Discovered during production environment testing. Unsure how exactly what inner exception caused this until this issue is resolved.

```
+ gosu root python /var/scitran/code/api/bin/database.py confirm_schema_match
Traceback (most recent call last):
  File "/var/scitran/code/api/bin/database.py", line 77, in <module>
    logging.exception()
TypeError: exception() takes at least 1 argument (0 given)

```

**Comment by nagem** [comment]
Fixed in https://github.com/scitran/core/commit/ffc150aaf96010e9d9e0f7becbb8f90c20a5a3c8

**Comment by nagem** [comment]
Let me know if there is anything else you need from me on this, otherwise feel free to close.

**Comment by ryansanford** [comment]
Fix is working as expected. Thanks!
