### ISSUE TITLE
Add links for history reasons in file.py upload voodoo

### ISSUE THREAD

**Issue by kofalt** [scitran/core#223]
@josschne @gsfr @nagem Ref this never-expected-to-be-responded-to PR that I filed on webapp:
https://github.com/moraes/webapp-improved/pull/12. If this jives with our current understanding of our override situation, we should probably throw a link in the comments on the upload voodoo in files.py. 

This is a ticket, rather than a tiny commit / PR, because I want to check with the team if a) my PR description is still correct as far as we know, b) what other links are useful for understanding our tempfile / memory form processing situation.

**Comment by coltonlw** [comment]
I added comments explaining why we do these tricky things in files.py including links to cgi and webob source
