### ISSUE TITLE
Change of authtoken index expire time causes conflict when index is already created

### ISSUE THREAD

**Issue by nagem** [scitran/core#224]
Caused by https://github.com/scitran/core/pull/218.

`OperationFailure: command SON([('createIndexes', u'authtokens'), ('indexes', [{'expireAfterSeconds': 604800, 'name': u'timestamp_1', 'key': SON([('timestamp', 1)])}])]) on namespace scitran.$cmd failed: exception: Index with name: timestamp_1 already exists with different options`

**Comment by kofalt** [comment]
Haha, amazing.

![](https://cloud.githubusercontent.com/assets/265071/14155901/5f2d52dc-f689-11e5-91a9-7b8de78632ae.gif)

I've never been thrilled with document expiry being handled by the database; I'll file a new ticket to track future improvements beyond this bugfix.

**Comment by nagem** [comment]
I'm currently implementing create_or_recreate_ttl_index, please let me know if you have any better ideas on how to handle this without completely changing how and where we do db initialization.

**Comment by nagem** [comment]
Mongo does not allow you to update a ttl index, and they suggest dropping the index and recreating it if you need to change the ttl

**Comment by kofalt** [comment]
That sounds like a good approach for now - in the ticket I just created & referenced I have a quick link to how we can get a list of indexes for a collection / database.

Most storage products have some mechanism by which you can upsert an index - lacking an obvious native feature, we'll probably end up with a few functions of the sort you're proposing.

**Comment by gsfr** [comment]
Ref my [recent comment](https://github.com/scitran/core/issues/225#issuecomment-203632576) on #225. Can we just solve #212 and then drop and re-create all indexes at start up - once?

**Comment by nagem** [comment]
A fix to #212 would solve this, but for now we'll merge #228 and remove that during the work for #212.
