### ISSUE TITLE
Index usage improvements and upgrades

### ISSUE THREAD

**Issue by kofalt** [scitran/core#225]
Partially inspired by #224.
1. I've never been thrilled by the database controlling document expiry, as I feel that's an abstraction violation. This feels very similar in nature to complex business logic being thrown in SQL triggers or scheduled tasks, which generally resulted in a mess. I'd like that logic to live in the API.
2. At least at one point in time, I was told that re-creating an index may drop it entirely and rebuild from scratch, which is embarrassing, if not currently a huge deal. There are [ways](https://docs.mongodb.org/manual/tutorial/list-indexes/#list-all-indexes-on-a-collection) to get a list of indexes, so we could get better at detecting indexes and only creating them on demand.

**Comment by gsfr** [comment]
Looks like Mongo folks don't think too much of [upserting indexes](https://docs.mongodb.org/manual/reference/method/db.collection.ensureIndex/).

Anyway, doesn't seem like a big deal to me. We have bigger fish to fry first. The DB does an ok job at managing expiration for us. It's not like we change the interval all the time.

Also, if we figure out how to initialize only once (#212), we can simply drop all indexes at startup before re-creating them. I'm not at all worried about a slight startup delay and we can `background` index creation if we care.

For historical reference, we used to set up indexes during bootstrapping, which was only happening once, but it was thought that the system shouldn't need external boostrapping to be operational. Also, now, bootstrapping no longer touches the DB directly.

**Comment by ryansanford** [comment]
@kofalt #2 isn't surprising in my experience with MS SQL Server, where updating an index is equivalent to a drop and create. It doesn't have a concept of a TTL index. Filtered indexes are close, however those are non-clustered, and only supports exact comparisons, no functions or ranges.

**Comment by kofalt** [comment]
In this case I was only referring to our behaviour, not the database's - we can avoid recreating indexes when they already exist with our desired characteristics

**Comment by kofalt** [comment]
![acceptance](https://cloud.githubusercontent.com/assets/265071/26690075/98746afa-46bd-11e7-835c-10627058dc7c.jpg)
