### ISSUE TITLE
JSON schema improvements

### ISSUE THREAD

**Issue by kofalt** [scitran/core#226]
Two goals:

1. Use a single source of truth
1. Eliminate need for network loopback.

Filed per request from team discussion, although this sat in my notes for awhile.

**Comment by kofalt** [comment]
Loopback continues to be a problem in my dev environment :disappointed: 
Will be happy to see this fixed.

**Comment by coltonlw** [comment]
@kofalt Would you consider this completed?

**Comment by nagem** [comment]
>Use a single source of truth 

I think we have the structure for that in place with the schema hierarchy @coltonlw added.
Seems pretty done to me.

**Comment by kofalt** [comment]
:+1:
