### ISSUE TITLE
Intent pattern for mongo query modification

### ISSUE THREAD

**Issue by kofalt** [scitran/core#227]
Right now, the permchecking and other operations are mainly via closure generators that can be wrapped inside each other. The team reacted positively to an alternative approach:

```
intent.get.query({}).permcheck({}).done()
```

Each successive call returns a new copy of an object recording the intent (query and its options), the final function maps everything together and returns the result.

Filed per request from team discussion, although this sat in my notes for awhile.

**Comment by rentzso** [comment]
What priority does this ticket have?
It doesn't seem to enable any new functionalities.

**Comment by gsfr** [comment]
@rentzso No priority. Just documenting a possible future enhancement.
