### ISSUE TITLE
Add Group Tags

### ISSUE THREAD

**Issue by mrDarcyMurphy** [scitran/core#229]
For https://github.com/flywheel-io/frontend/issues/127

We need the ability to save tags to a group. If a tag is deleted it needs to be removed from that group's children. 

@rentzso and/or @nagem, anything else this needs?

**Comment by nagem** [comment]
I think we're good. @rentzso started work for the change on the [add-tags-to-groups](https://github.com/scitran/core/tree/add-tags-to-groups) branch if you wanted to take a look. I'll be finishing it up (mostly cascading removal of tags).

**Comment by mrDarcyMurphy** [comment]
@nagem Ok. I assume that any change will need the whole tag array to be sent. Is that right?

**Comment by rentzso** [comment]
@mrDarcyMurphy tags on groups will be handled as any other list. So you have to send just the tag you need to create or delete.

**Comment by mrDarcyMurphy** [comment]
@rentzso Cool. It's working well so far. 

One thing I caught was that sending a duplicate tag returns a 404. Not sure if that's the right code or not. Regardless, I'll try and check for uniqueness before sending anyways.

**Comment by mrDarcyMurphy** [comment]
@nagem I've got a weird bug where some tags aren't deleted. I haven't found any difference between the delete requests that work and those that don't, but I can still reproduce the bug if you want to take a look.

**Comment by nagem** [comment]
@mrDarcyMurphy

**Comment by mrDarcyMurphy** [comment]
@nagem I'd love to, but don't really have any. I'll stop by your desk.

**Comment by mrDarcyMurphy** [comment]
@nagem Got another one for you: When adding a tag to a session the API doesn't care if the tag exists on the group or not. That's intentional, as far as I know. I'm not sure if it _should_ be though.

**Comment by nagem** [comment]
@mrDarcyMurphy Considering the group tags are being used as a "tag pool", I don't believe that should be allowed. I think @rentzso suggested adding that restriction to `consistencychecker.py`.

**Comment by rentzso** [comment]
if we have dynamic json schemas, this could be better handled as an enum.
But I am not sure it's good to enforce this.
Maybe yes but there could be other clients that don't want to use the "tag pool" feature.
@gsfr what do you think about this?

**Comment by gsfr** [comment]
I think it's fine the way it is. The application can treat the group tags as a tag pool for its decedents, but the api won't know or enforce that. For the api, they're just group tags.

We can still do recursive deletion, if desired, because recursive operations are a general feature that the api should offer.

In discussing with @rentzso, one interesting edge case we need to keep in mind is moving a tagged session from one project (and group) to another project (in another group). What if that other group doesn't have the right tags. Again, I think that's fine. Don't do anything special. After all, accidentally moving a session to another project and then back, and loosing all your tags in the process, would be rather annoying.

**Comment by nagem** [comment]
@mrDarcyMurphy Could you add any remaining changes to the API to this list?

[] Deleting a group tag deletes the tag down the heirarchy
[] Renaming a group tag renames tags down the heirarchy

**Comment by mrDarcyMurphy** [comment]
@nagem I think that's it for now. I'll let you know if I think of anything else.

I have some info for that delete bug too. It only works if the tag is three characters or longer. If the tag is only 1 or 2 characters then it can be created but not deleted.

**Comment by nagem** [comment]
And that bug makes sense if you look [here](https://github.com/scitran/core/blob/master/api/api.py#L64). 

@rentzso any reason we can't move this to to 1-24? We should also change tag.json to reflect what kind of restrictions we decide on for length.

**Comment by rentzso** [comment]
@nagem no reason. Please just make a test with a one letter tag, so that we don't fall in any weird edge case.
You can modify https://github.com/scitran/core/blob/master/test/integration_tests/test_tags.py for this purpose.

**Comment by mrDarcyMurphy** [comment]
@nagem My spec says 32 characters. I don't care which it is, just want to be consistent.

https://github.com/flywheel-io/frontend/issues/127

**Comment by nagem** [comment]
32 is fine, let's go with that. All tags must be 1-32 characters long and may not contain `/` characters.

**Comment by nagem** [comment]
@mrDarcyMurphy All changes should be available in this branch, opening a PR now - let me know if anything isn't working as expected.
