### ISSUE TITLE
Create restrictions on file fields

### ISSUE THREAD

**Issue by nagem** [scitran/core#231]
Use an enum in our input json schema to restrict values saved to type and modality fields

**Comment by nagem** [comment]
Also incorporate https://github.com/scitran/core/issues/210

**Comment by nagem** [comment]
@gsfr I had written down file type, modality and "instrument" when I think perhaps I meant measurement? Please confirm the fields we want to restrict to a list of approved values when you get a chance.

**Comment by gsfr** [comment]
Yup. File type and modality are easy. Measurement is harder, because it depends on modality.

**Comment by nagem** [comment]
Encompassed/replaced by #649
