### ISSUE TITLE
Prototype: Dynamically build json schema files using Jinja2

### ISSUE THREAD

**Issue by nagem** [scitran/core#235]
This would potentially allow us to solve several problems with our current json schemas:

 - Combine input and mongo schemas
 - Combine redundant schemas like [uidupload](https://github.com/scitran/core/blob/more-uploads/api/schemas/input/uidupload.json) and [labelupload](https://github.com/scitran/core/blob/more-uploads/api/schemas/input/labelupload.json)
 - inject custom enums, like allowable tags for a group

Would solve issues noted in #226

**Comment by coltonlw** [comment]
@nagem Thanks for taking the time to implement $ref support from the filesystem
