### ISSUE TITLE
Collections acq endpoint is missing the join-origin

### ISSUE THREAD

**Issue by dpuccetti** [scitran/core#242]
When calling /collections/cid/acquisitions?session=sid&join=origin the join-origin field is not included in the response.  This prevents the UI from being able to display the origin icons.

The join-origin field is added to the response from /sessions/sid/acquisitions?join=origin as expected.

**Comment by kofalt** [comment]
Join logic is in `ContainerHandler.handle_origin`, probably just needs to get called for collections as well.
