### ISSUE TITLE
General API Usability Improvements

### ISSUE THREAD

**Issue by nagem** [scitran/core#243]
After a discussion with @dpuccetti @mrDarcyMurphy @kofalt, this is a list of API improvements that would make frontend dev easier. This ticket could be turned into an epic when prioritized: 

 - [ ] Send empty array for subdocument field instead of missing array (rolled into #189) 
 - [ ] Documentation (ref #63)
 - [x] Ability to return all permissions for requests that return lists when user is operating as admin (rolled into #189)
 - [ ] Add pagination to requests that return lists

**Comment by gsfr** [comment]
Empty subdocuments and subarrays are guaranteed per our data model. I'm surprised to hear that this is not upheld in practice. Should be easy and fast to fix. @nagem Can we make it part of the v2 migration?

*[ignores the d-word]* 😉 

Does the permissions item refer to *list* queries? Should already be true for *detail* queries. Could be solved by a simple query param that prevents permission stripping. @rentzso Complexity?

Pagination has been on our list for a long time. I'm not opposed, but I'm also not convinced it will solve any user's problems. Filtering, for instance, will need to be moved server-side. It's certainly more complex than simply returning the first *n* items.

For reference, the 1627 sessions we have in the Stanford instance only amount to 80Kb, an come out in less than 200ms. I'm guessing we don't even have the right index on the perms. Should we just do pagination in the UI?

**Comment by rentzso** [comment]
for list queries adding a query param switch should be a one line addition in containerhandler and collectionshandler.
For detail queries, the full list of permissions is already returned for superuser requests.

**Comment by nagem** [comment]
@rentzso, I edited the list above to specify that permissions were requested for `get_all`s, thanks for clarifying.

**Comment by nagem** [comment]
>Can we make it part of the v2 migration

Sure can.

**Comment by nagem** [comment]
I updated https://github.com/scitran/core/issues/189 to have a clear list of what changes it includes. Let me know if we want to remove the final two checkboxes I added from this list.

**Comment by gsfr** [comment]
I would support closing this ticket when 1 and 3 are done. Documentation is already tracked as noted above. And we may or may not open a ticket for pagination, pending a discussion with the UI team.

**Comment by nagem** [comment]
Since 1 and 3 are being rolled into #189, I'm also fine just closing it now. 2/4 ain't bad @dpuccetti @mrDarcyMurphy ¯\\\_(ツ)\_/¯.

**Comment by mrDarcyMurphy** [comment]
1. An empty array for a subdocument field won't make a large difference, we'll have to do a different (or maybe an additional) null check. Feeling ambivalent about this one.
2. It's tedious, but we'd all benefit from good documentation. The exercise of writing the docs and testing  the API may elucidate further ways it can be improved. Eventually a customer will be curious about it too. Luck favors the prepared.
3. WOOT! This will be really helpful.
4. I'm looking forward to this as well, but I think we all agree that it's a large-ish project that spans across teams.

So, yeah, I'm fine with closing this too.

**Comment by mrDarcyMurphy** [comment]
@nagem Here's one: better error messages. While building a feature I ended up trying to add a user to a group that was already in the group. The response was:

```
HTTPNotFound: Element not added in list roles of container groups foo
```

404 seems like the wrong error code for that, and it would've been more helpful if it told me why the request was rejected not merely that it was (ie. "User is already in that group").

**Comment by nagem** [comment]
@mrDarcyMurphy I'm going to quote your comment in #66 where we are tracking some major error-handling work and then close this ticket.
