### ISSUE TITLE
Add a disabled flag to users

### ISSUE THREAD

**Issue by elisapoquette** [scitran/core#247]
Need to be able to disable users in the system. When finished, notify Elisa and she will create frontend ticket.

**Comment by nagem** [comment]
Referencing #252, which of these requirements for permanently deleting a user would we want to apply for disabling a user?

> - remove user from all group roles
> - remove user form all project permissions
> - remove user from all collection permissions
> - delete all collections where user is curator 

If we do not intend to create a way for site admins to delete users, I believe we should remove user's permissions/roles for sure, not sure about collections as those are intended to be shared.

**Comment by gsfr** [comment]
I was thinking, none. Disabling a user should be fully revertible. Say, if they haven't paid their bill.

**Comment by nagem** [comment]
We could leave cleaning up permissions to group and project admins, for example a user that has left the organization.

**Comment by elisapoquette** [comment]
They may or may not want to clean up permissions for a disabled user (depending if a user comes back). To me, disabled users are just blocked from logging in. Deleted users are removed from groups, projects, collection and no longer have an account.

**Comment by nagem** [comment]
@elisapoquette this is now merged, feel free to create a frontend ticket.
