### ISSUE TITLE
Can't fetch group details when user has only read or read/write access.

### ISSUE THREAD

**Issue by mrDarcyMurphy** [scitran/core#249]
This is to support dashboard filtering on https://github.com/flywheel-io/frontend/issues/127.

At this point the `/api/groups/foo` request fails with or without the `?root=true` query parameter. So a user could be a member of a group and be unable to use that group's tags for filtering.

Would it be possible to return the tags on the groups when GET'ing `/api/groups`? I'm open to suggestions though.

**Comment by elisapoquette** [comment]
@nagem can you check this out? We have a feature on the frontend that depends on this and I would like to get it wrapped up as soon as possible. Thank you!

**Comment by nagem** [comment]
The only fields on groups are `name`, `roles`, `tags` and `id/created/modified`. I think if we strip out `roles` unless you are requesting as `?root=true`, we can return the entire group to anyone with read access. I'll make that change now.

**Comment by mrDarcyMurphy** [comment]
@nagem Ok, thank you. That'll help a lot.

**Comment by nagem** [comment]
@mrDarcyMurphy take a look at #251 and branch `group-tag-perms`

**Comment by gsfr** [comment]
Any reason to deviate from our typical pattern here? You get your own role, if you are a member, but not an admin; you get all roles, if you are an admin or root=true.

**Comment by nagem** [comment]
@gsfr my comment above isn't very clear. `/api/groups` and `/api/groups/foo`now both return the entire group object with `roles` filtered to just your permissions. When `?root=true` is added, `/api/groups` returns all groups and all permissions, `/api/groups/foo` returns all permissions.

**Comment by nagem** [comment]
Final decision on when perms return and when they do not - they will behave exactly like container permissions: users will receive full permissions lists for groups where they are an admin, for singular and list GETs. All groups with all permissions will be returned when using `?root=true`.
