### ISSUE TITLE
Group admin's can't delete their group.

### ISSUE THREAD

**Issue by mrDarcyMurphy** [scitran/core#250]
A Group Admin that isn't a Site Admin can't delete groups they're an admin of. Only Site Admins can delete groups.

Is this intentional?

**Comment by elisapoquette** [comment]
I believe so - only Site Admins can create and delete groups according to the permission matrix. This should be consistent with Project, where only Group Admins can create and delete (empty) projects.

**Comment by mrDarcyMurphy** [comment]
Ok, thanks.
