### ISSUE TITLE
Add endpoint to permanently delete a user

### ISSUE THREAD

**Issue by gsfr** [scitran/core#252]
Add `DELETE /users/<uid>` endpoint for internal maintenance. Require `root=true`. Eventually, this endpoint may be exposed to site-admins in the UI.

Before actually deleting the user, this endpoint needs to do the following:
- remove user from all group roles
- remove user form all project permissions
- remove user from all collection permissions
- delete all collections where user is curator

Relates to #247. Ping @ryansanford, @lmperry, and @nagem. Medium priority and straightforward. Should be prioritized when an equivalent maintenance script would need to be written instead.

**Comment by nagem** [comment]
Ran into a snag with cleaning up collections - we do not store the creator as `curator`, as you can see [here](https://github.com/scitran/core/blob/59e35687bd433872889e42dae8c23938450ff2a8/api/handlers/collectionshandler.py#L34-L38)

**Comment by nagem** [comment]
Created a ticket for missing curator field https://github.com/scitran/core/issues/263.

We could land #263 before this issue to ensure we cleanup collections properly when this lands, or use the logic defined in #263 to clean up collections on user delete until #263's update script fixes it for all collections.
