### ISSUE TITLE
Add unique subject id

### ISSUE THREAD

**Issue by gsfr** [scitran/core#253]
When creating a new session in the DB, add an `_id` field of type `ObjectId` to the `subject` subdocument.

If another session with the same `subject.code` already exists in the new session's project, copy the `subject._id` from the existing session, else generate a new one.

Also, allow `subject._id` to be set explicitly on new and existing sessions via `/sessions`.

**Comment by nagem** [comment]
`hierarchy.py`, `placer.py`, and `containerhandler.py/containerstorage.py` all create session objects in mongo and will need this new logic. Will do code search to try to find any other instances.

**Comment by nagem** [comment]
An imperfect search of the keyword `insert` looks like above are the only locations a session is created.

**Comment by nagem** [comment]
@gsfr We don't require a subject in creation of a session, and subject `codes` and `projects` can be changed. There will be subjects without `_ids` and subjects with the same `_id` but different `codes` and/or `projects`. I am wary of trying to make this a perfect system by adding functionality to `PUTs` to try to keep everything in line.

**Comment by gsfr** [comment]
Thanks, Megan. I think that's all fine. The idea behind the `subject._id` is to be unique across sessions, even if the `subject.code` isn't, and also to span projects, if manually updated. If no `subject` is given when creating a new `session`, just generate a fresh `subject._id`. Only copy an existing `subject._id` if the same `subject.code` already exists in the new session's project
