### ISSUE TITLE
Replace mongo generated ids where more secure uuids are necessary 

### ISSUE THREAD

**Issue by nagem** [scitran/core#255]
Review code and replace any usage of mongo generated ids that should be uuids generated in code instead. 

Mentioned in 4/15/16 planning meeting.

**Comment by kofalt** [comment]
Note that this will mean a database version bump + transform, if any keys were ObjectIds but will no longer be

**Comment by nagem** [comment]
Looking over the codebase we properly store tokens for uploads and downloads with a generated uuid. One change that will need to be made is [here](https://github.com/scitran/core/blob/master/api/upload.py#L335) where we are transforming the token into a bson ObjectId before querying. That can get fixed as part of #294
