### ISSUE TITLE
Version collection missing from running instance

### ISSUE THREAD

**Issue by kofalt** [scitran/core#261]
On a running dev instance, I would expect a `{'_id': 'version', 'database': 2}` document to exist in the `version` table, but no `version` table exists:

![screenshot-area-2016-04-22-141624](https://cloud.githubusercontent.com/assets/265071/14752437/de9aed82-0894-11e6-89a4-ad7861e2c1d8.png)

**Comment by nagem** [comment]
This was changed in flywheel-io/flywheel#173, closing.
