### ISSUE TITLE
Store collection creator as 'curator' during POSTs

### ISSUE THREAD

**Issue by nagem** [scitran/core#263]
We are currently adding the user as admin in a collection's permissions list instead of saving their `uid` as `curator`. 

See here: https://github.com/scitran/core/blob/59e35687bd433872889e42dae8c23938450ff2a8/api/handlers/collectionshandler.py#L34-L38

If there is only one admin in the permissions list we can probably assume they are the curator and fix this in a db update script.

**Comment by gsfr** [comment]
We should set the curator in addition to setting the admin permission, not instead.
