### ISSUE TITLE
Audit all optional parameter default values for mutability

### ISSUE THREAD

**Issue by kofalt** [scitran/core#269]
Today I learned about this: https://stackoverflow.com/questions/1132941/least-astonishment-in-python-the-mutable-default-argument 

Aggravating, but not without humour :smile: 

![screenshot-area-2016-04-29-141313](https://cloud.githubusercontent.com/assets/265071/14926950/9d8967a8-0e14-11e6-9a40-360ddc3f4a0d.png)

This has already caused at least one bug - `tags=[]` in `jobs.queue_job` - and I know that I've personally written a decent amount of code with optional params. I don't know what else might need fixing.

For now, I'll leave this ticket assigned to me until I've cleared out `jobs.py` and `rules.py`, then probably assign to @nagem for handling at your discretion.

**Comment by gsfr** [comment]
Thanks for the link, @kofalt. Remind me again, why is this crazy language so popular? ;-)

Anyway, as the docs point out, `None` is the only safe default value. We may need sister tickets for this issue in other repos. I'll take on reaper in scitran/reaper#21.

**Comment by kofalt** [comment]
In discussion with @aaltepet, we seemed to think that primitives were also safe.
Do you think that's accurate?

**Comment by gsfr** [comment]
Good point. It should be true for anything that's not implemented as a pointer. Not sure what that entails, beyond [numeric types](https://docs.python.org/2/library/stdtypes.html#numeric-types-int-float-long-complex).

**Comment by kofalt** [comment]
The `jobs/` module is clear. Assigning to @gsfr for you to decide the next steps.

**Comment by gsfr** [comment]
According to pylint,
dangerous: `[], {}`,
safe: `None, False, 0, 0.0, '', ()`.

Ran pylint, got one hit for `dangerous-default-value` in api/base.py:320.
```
def schema(self, updates={}):
...
```

Looks like that method is never called. @nagem, @rentzso Ok if we simply remove the method?

**Comment by nagem** [comment]
SGTM. It didn't appear to be used in my investigation either.

**Comment by gsfr** [comment]
PR #307 opened. We're also bringing in pylint permanently as part of #300.
