### ISSUE TITLE
Remove jobs.add_raw

### ISSUE THREAD

**Issue by kofalt** [scitran/core#273]
Awhile after #270 lands & confirmed working, we should remove `jobs.add_raw` for obvious reasons :)

**Comment by kofalt** [comment]
The eagle has landed; @lmperry let me know when your usage of `add_raw` is ported to `raw`. No rush, but I'd like to remove that endpoint sooner or later. Maybe it'll mysteriously disappear at the end of May? ¯\\_(ツ)_/¯

**Comment by lmperry** [comment]
Feel free to remove it.
