### ISSUE TITLE
Fix zipfile import error, cleanup FileListHandler responses

### ISSUE THREAD

**Issue by nagem** [scitran/core#283]
Using any of the optional params on `FileListHandler.get` result in a 500 as the `zipfile` lib is not being imported.

While looking into this error I noticed our responses for `GET` on a file with the params `info=true` or `comment=true` are not JSON. That should be cleaned up.

**Comment by gsfr** [comment]
Thanks, Megan. Just talked to @rentzso. Here is our proposal:

```
GET .../files/<filename>?info=true =>

{
"comment": string,
"members": [
  {
      "path": string,
      "size": int,
      "timestamp": isotimestamp,
      "comment": string
    },
    ...
  ]
}
```

We're not currently using the [member comment](https://docs.python.org/2/library/zipfile.html#zipfile.ZipInfo.comment), but I suggest we include it for completeness.
