### ISSUE TITLE
Label uploads creating separate projects when project names contain special characters

### ISSUE THREAD

**Issue by gsfr** [scitran/core#284]
When using the folder uploader to hit the label upload endpoint and project labels contain special characters, such as parenthesis, a separate project is created for each acquisition.

To reproduce, rename the `Testdata` project in our standard test data to `Testdata (0)` before bootstrapping.

**Comment by nagem** [comment]
We're using a regex in the query for the project:
`'label': {'$regex': project_label, '$options': 'i'}`

We should escape `project_label` with `re.escape()`
