### ISSUE TITLE
Ensure timestamps on sessions and acquisitions are an ISO formatted string (or null)

### ISSUE THREAD

**Issue by nagem** [scitran/core#292]
After a discussion with @rentzso about improperly formatted timestamps causing ElasticSearch headaches, a few places need to be changed:

`"timestamp":    {"type": ["string", "null"]}` needs to become `"timestamp":    {"type": "string", "format": "date-time"}` in:
 - input/session.json
 - input/acquisition.json
 - input/uidupload.json
 - input/labelupload.json
 - input/enginemetadata.json
 - mongo/session.json
 - mongo/acquisition.json

Checks for timestamps in session/acquisition creation in hierarchy.py need to look for `None`.

@rentzso please fill in any missing details for this ticket.

**Comment by rentzso** [comment]
Adding that checks for timestamps needs to be fixed also in `download.py`, `'listhandler.py` and `containerhandler.py`.

**Comment by nagem** [comment]
Adding `"minlength": 1` should eliminate any empty strings so we don't have to check in code.
