### ISSUE TITLE
Disable job retry when explicitly failed

### ISSUE THREAD

**Issue by kofalt** [scitran/core#314]
Retrying a job is an important & necessary feature when a job is orphaned.
This contrasts with all other failure scenarios that I'm currently aware of, which are not transient:

1. Gear is invalid
1. API-level incompatibilities
1. Bad environment (gears not available, corrupt, code issue, etc)

In all these scenarios, it doesn't make sense to spam a bunch of job failures.

I propose that we disable the [Queue.mutate](https://github.com/scitran/core/blob/582dffac908d0de250758babfda74f0e012e50d9/api/jobs/queue.py#L67-L69) retry logic.
The [restart-orphan](https://github.com/scitran/core/blob/582dffac908d0de250758babfda74f0e012e50d9/api/jobs/queue.py#L214-L216) behaviour would remain the same.

Relevant to @lmperry, @ryansanford. Assigning to @gsfr for team discussion.

**Comment by ryansanford** [comment]
Maybe retry concern is outside scitran/core, since scitran/core only persists the queue, but all workers are external. We now have a job creation endpoint where engine can create new "retry" jobs if it sees fit, yes?

**Comment by kofalt** [comment]
The `/jobs/add` endpoint currently doesn't accept a `previous_job_id` key, and I don't think we should add one because retrying a job creates an identical copy.

Instead, we could add a `/jobs/x/retry` endpoint, with the same permissions as `/jobs/add`, that will retry job X if X is in state `failed` and no other jobs have X as a `previous_job_id`.

The engine currently doesn't know anything about the core's queue, and I would be hesitant to change that right now. But I would be open to some other part of our architecture (an admin panel? a retry button on the UI?) having that functionality.

**Comment by gsfr** [comment]
I agree. Jobs should only be retried under a controlled set of circumstances. Initially, that set could be limited to orphaned jobs. Another, future, reason might be "external resource unavailable". Let's make sure we keep the door open for future enhancements of this sort, using special exit codes or the like.

I'd also like to see the attempt concept moved into the job. If we need to run a job twice, that's two *attempts*, not two *jobs*.

**Comment by kofalt** [comment]
Aside: retry endpoint landed as #316, so admin panel / etc bits could now be rigged up if desired.

This is a good opportunity to put some queue configuration into the database - there's a `MAX_ATTEMPTS` integer that's been wanting that for awhile. I'll move that, and add a key that disables retries entirely when explicitly failed. Pending disagreement, that will be default behaviour.

Assigning to me for implementation.
