### ISSUE TITLE
/api/gears/(gid) route does not work when there is no gears document

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#330]
On a new instance of scitran/core when there is no `gears` document yet in the singletons collection, POSTing to /api/gears/(gid) returns a HTTP 200, but no `gears` document is created.

Integration tests for this route should be added, and would have caught this issue.

**Comment by kofalt** [comment]
Quick fix was added with 4a32bbd, no tests at the moment

**Comment by nagem** [comment]
`gears` and `rules` have their own collections in mongo now and have extensive integration tests.
