### ISSUE TITLE
Job-based Analyses

### ISSUE THREAD

**Issue by nagem** [scitran/core#332]
Allow for the creation of analyses that are tied to a specific job, with the analysis being the job's output destination. This will be a first pass to get things working for now. A reworking of both types of analyses, using what we learned from these two prototypes, is expected to be done soon after. 

 - [x] Create a new endpoint that creates a new analysis and job, then ties them together via the job field on an analysis and the destination of the job
 - [x] Create a new logic flow for `/api/engine` where `level=analysis`
 - [x] Create a new placer that inherits from AnalysisPlacer, used for uploads coming from the engine
 - [x] Modify all `GETs` to return both types of analyses the same way
 - [x] Modify download endpoint to work for job-based analyses

**Comment by nagem** [comment]
Ran into a snag with permissions, talked it over with @elisapoquette. Synopsis of discussion:

1. Bob has access to Proj1 and Proj2. Alice has access to Proj2 only.
1. Bob creates an analysis on a session in Proj2 tied to a job.
1. Bob chooses a file from an acquisition on Proj1 for one of the inputs to his job.
1. Alice loads the analysis from Proj2 (legal, as she has access to it's session).
1. The API now needs to inflate info about the job's input files, but Alice does not have read access to this information.

For the short term, we will fill in the file info and add a flag marking it as read-only. The frontend can alter the display of this file if they wish. The file will not be included in the bulk download endpoint. 

@gsfr or @lmperry let us know if you have any issue with the plan or any other ideas.

**Comment by gsfr** [comment]
This is much broader than we originally envisioned. Inputs are always to be chosen from a single container, initially just sessions. Projects are a straightforward extension as the permissions are clear.

For collection-level analyses, the same permissions issues will apply as do to collections themselves. Appropriate warnings for the creator or sharer of the collection/analysis as well as proper rendering of inaccessible items will be needed. To get us started down this path, I'll add a ticket for warning a user, who shares a collection with another user who won't have access to all data in that collection.

**Comment by nagem** [comment]
That's a fair assumption - I'll remove that permissions checking. Our API does allow you to specify inputs from anywhere, though. Instead that might need to be tightened up.
