### ISSUE TITLE
Discussion: Add rule support for depending on jobs

### ISSUE THREAD

**Issue by kofalt** [scitran/core#364]
Another entry under the "we don't have a graph for something that is a graph" category.

At the moment, our nascent rule system only allows jobs to be triggered on files. This works for a `dicom comes from space --> convert to nifti --> do something with the nifti` workflow, but does not work for workflows that involve classifier gears. If a gear only uploads metadata, there is no change as far as the rules system is concerned. This is a blocker for improving the nifti QA gear.

Without invoking a larger overhaul, I propose:
1. Add a rule type that requires the file's container to have a job with state `complete` and name X. 
2. Implement the rule type using `Queue.search`. Call it `container.has-job`.
3. Add code path for `rules.create_jobs` to be called whenever a job completes.
4. Maybe have a look at `queue_job_legacy`? Can we put that to rest yet? Maybe not.

Blocks scitran/apps#19.

**Comment by ryansanford** [comment]
@kofalt 
Thanks for logging this, I assumed an issue already existed.

Does the option of triggering rules from file object meta updates fall into your label of "larger overhaul"? Having different rule types for "process new file with ..." vs. "process job result with ..." seems like a burden. @gsfr  and @lmperry are closer to the users and use cases than myself, so I welcome their design input.

**Comment by kofalt** [comment]
Yes, in part because we don't have a job graph. But metadata (now info) breaks the mold in several ways:

1. Populated asynchronously w/r/t file upload
1. Can be populated multiple times
1. Can be updated redundantly, and / or a partial or complete clobbering of older data

This makes it difficult to have any job triggered from this field, or others like it: exactly-once trigger semantics looks possible, but definitely irritating and error-prone given the above.

You can sort-of reproduce a job graph by doing lots of container queries on the jobs table. I'm not enthusiastic about that, and we'd have to make a bunch of policy decisions (Does a human editing metadata trigger a job? What kind of edits from which sources trigger, and can some of those trigger redundantly?).

**Comment by kofalt** [comment]
To illustrate, I think this function would need to be filled out:

```python
def decide_jobs_from_info(container, file_obj, old_info, new_info):

    # find the set of jobs that have (possibly) consumed /produced this file?
    # investigate the diff, what should the result info be? (partially decided elsewhere)
    # which jobs would now be triggered given the result info?
    # of those, which jobs should actually run?

    return jobs_array, result_info
```

**Comment by kofalt** [comment]
The more I think about it, the more this gets in the way of using gear manifest inputs as a replacement for the gear rule system. That's not great. We may have to tinker with parts of that, or have an escape valve.

**Comment by gsfr** [comment]
Please schedule a half hour call no sooner than Thursday, if you need my input on this.

**Comment by ryansanford** [comment]
I'm going to try and schedule something today to nail down a path forward. Peking U has a gear they want automatically run only on diffusion dicoms.

**Comment by gsfr** [comment]
I believe our takeaway from today's meeting was that we will try a *classification*-based rule, despite a theoretical risk of an infinite processing loop.

@ryansanford will try this with the current QA gear, which should only be run on *functional MR* data. Ideally, we'd also take the *instrument* into account.

**Comment by kofalt** [comment]
> despite a theoretical risk of an infinite processing loop.

That will not be the case if we keep the same policy decision I proposed in the meeting: that a gear will only be ran if the **old** file document does **not** match the rule, and the **new** file document **does** match the rule, which is possible with the above function signature.

**Comment by gsfr** [comment]
@kofalt I understand. But that's not the case we have today, with zero code change.

**Comment by kofalt** [comment]
Hmm. I hope it'd be pretty easy to plug in, but go ahead & try without it if you prefer. My guess is that it'll cause infinite loops on our test data, but there's one way to find out :slightly_smiling_face:

**Comment by kofalt** [comment]
@lmperry I'm going through old tickets, and thought this might be interesting reading, as I've heard that you might be re-raising the idea of pipelines. Read or ignore as desired!

**Comment by nagem** [comment]
From the original: 

>If a gear only uploads metadata, there is no change as far as the rules system is concerned.

This is no longer true, and we can trigger jobs off any file in the acquisition changing in any way. The method idea `decide_jobs_from_info_change` has been added, although slightly modified from the description above. 

Pipelining (via jobs or templates) is still under consideration, but I think the original spirit of this ticket has been fulfilled.

**Comment by kofalt** [comment]
Disagree a bit: I think we need to keep this open for now, in particular for SDK gears that may interact with external systems.
