### ISSUE TITLE
Discussion: rename file / other model properties to avoid json schema reserved keywords

### ISSUE THREAD

**Issue by kofalt** [scitran/core#379]
Our [file data model](https://github.com/scitran/core/blob/master/api/schemas/input/file.json) has a `type` key in it, which is awkward when writing a [schema snippet](https://github.com/flywheel-io/gears/tree/master/spec/v0#the-manifest) that matches part of it.

I don't have a list of json-schema reserved keywords in front of me - it might rightly be described as the set of all schema directives (including optional ones), which I think means we go through the spec and compile that list. Maybe someone's better at google than me.

To close this ticket:

1. Compile & post (as a comment on this thread) the set of reserved keywords
1. Find & post the set of conflicts with our data models
1. Land a PR that changes those fields & upgrades the database.

**Comment by kofalt** [comment]
I tentatively propose we replace `file.type` with `file.stype`, aka "scientific type". (dicom, etc)
Contrast the existing `file.mimetype`.

**Comment by gsfr** [comment]
SGTM, although I'm opposed to `stype`. It's cryptic and misleading. Referring to our [list of filetypes](https://github.com/scitran/core/blob/master/api/files.py#L247-L269), items like "presentation" or "video" are not scientific types by any means.

The best thing I can come up with is `file.kind`.

**Comment by kofalt** [comment]
That works for me, pending it not randomly being a reserved keyword either :D

**Comment by kofalt** [comment]
No pressure, but this will make some upcoming CLI stuff a lot nicer.
Any chance we could bump this / combine it with DMv2?

**Comment by gsfr** [comment]
I would be fine with that. Probably less work for the UI team, as well.

@nagem: Thoughts?

**Comment by nagem** [comment]
I probably won't get to it until early next week, but should be easy to combine it will DMv2.

**Comment by nagem** [comment]
Work is done in branch `file-to-kind-rename`.

Working with @kofalt currently to determine if this rename is necessary.

**Comment by nagem** [comment]
Resolved by modifying the [manifest schema](https://github.com/flywheel-io/gears/compare/v1)
