### ISSUE TITLE
Misc Search enhancements

### ISSUE THREAD

**Issue by elisapoquette** [scitran/core#387]
_API Changes_

- [x] Inability to Search analysis containers
- [x] Can't search on null or missing fields  
- [x] Inconsistent wild cards

**Comment by elisapoquette** [comment]
@nagem the above are issues that have been identified as creating usability problems with Search. Lets's discuss - I would like to make these updates by end of next Sprint.

**Comment by nagem** [comment]
I'll review with @rentzso.

**Comment by nagem** [comment]
I'm not sure I understand this request:
> Search for collection curator (returning files) doesn't return results if there are no sessions/acquisitions in that collection

**Comment by nagem** [comment]
As to searching for a `null` or missing field, the frontend could make a query request similar to the one documented [here](https://www.elastic.co/guide/en/elasticsearch/guide/current/_dealing_with_null_values.html#_missing_query)

Elastic handles missing fields and `null` fields the same.

**Comment by nagem** [comment]
Wildcard characters (specifically `*`) should not be necessary as a the a search for `loc*` and `loc` will return the same results.  

A search like `loc*nt` is a whole different can of worms but I don't think we have a need for that.

**Comment by nagem** [comment]
Will review how reducing the `min_gram` length to 2 will affect indexing time on larger datasets.

**Comment by elisapoquette** [comment]
@nagem any update on reducing the length to 2 characters? I would like to close out this ticket
