### ISSUE TITLE
Standardize docstring format in codebase

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#391]
There are two main docstring formats for Python that sphinx can render into HTML:

reStructuredText: 
https://www.python.org/dev/peps/pep-0287/ 
https://pythonhosted.org/an_example_pypi_project/sphinx.html
http://thomas-cokelaer.info/tutorials/sphinx/docstring_python.html

Google style:  http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

Both of these can be rendered by Sphinx into HTML module documentation.  The reStructuredText format is the "official" format, although google-style is also widely accepted.  I am fine with either, although I might recommend reST format as I think it offers better control of formatting and links, and is the officially supported format.  

@ryansanford @gsfr @nagem @kofalt  I'd like us to pick one of these two formats so we are able to generate HTML module docs and be consistent with our docstrings.   I will use the chosen format to document the testing utilities I'm prototyping for us right now, and in the future I can help add/convert docstrings.  Does that sound OK and what are your thoughts on which format we should use?

Note:  This is for module interface documentation, not HTTP API documentation.  

After this issue is closed we can consider using https://readthedocs.org/ to generate and host HTML module interface docs.

**Comment by kofalt** [comment]
I'm happy with either and defer to the others tagged :)

**Comment by gsfr** [comment]
I'm also happy to go with either format. Since I don't have any firsthand experience, I'll support whatever you choose, @coltonlw.

Re readthedocs.org, we should also consider building docs ourselves, using travis, for instance, and pushing to scitran.github.io/docs or similar.

It would be nice to refresh what's on scitran.github.io/.

And we also have control over scitran.io, which currently redirects to scitran.github.io. Happy to hear suggestions on how to best utilize all those URLs. Probably in another ticket.

**Comment by coltonlw** [comment]
Sounds good, build the docs ourselves, readthedocs can be finicky sometimes anyway.  Regarding the format, after sleeping on it I've decided the Google style would be better for us, it is way easier to read in the code and I think that's important.  I will use google style docstrings for the testing utilities I'm building and then everyone can take a peek when I present my plan for testing.

**Comment by ryansanford** [comment]
FYI -- `docs/build-docs.sh` will build the docs. Currently the default entrypoint for the docker image runs this script and uwsgi hosts them at the URL path /api/docs/index.html

**Comment by coltonlw** [comment]
I would like to use Google style docstrings, as I mentioned before it's more readable in the code. Closing this, if anyone has more input feel free to re-open
