### ISSUE TITLE
Authentication not required by default

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#392]
Our api does not have a decorator or base view class that provides a "requires login" functionality.  Endpoints requiring authentication do this at the same time they do authorization, for instance by calling userauth.default() .  This can happen at any point in the view function, and sometimes it happens later on the view function because other information is required to do authorization.  Endpoints behaving this way allow unauthenticated users to make requests and will act on those requests, up until the point authorization code is called.  Any endpoint requiring authorization should require authentication as the very first step.  See PUT /users/{UserId} for an example of how this vulnerability allows an unauthenticated user to brute force the UserId of another user 

https://github.com/scitran/core/blob/master/api/handlers/userhandler.py#L94

EDIT:  We do have require login functionality, however it must be explicitly called by each private view and some views do not do this or do it after some processing has already been done

**Comment by coltonlw** [comment]
Demonstration with curl:

`(pyraml) Coltons-MacBook-Pro:raml coltonlw$ curl -k -D - -X PUT https://docker.local.flywheel.io:8443/api/users/lwcolton%40gmail.com

HTTP/1.1 404 Not Found
Server: nginx/1.9.3
Date: Wed, 10 Aug 2016 18:20:14 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 68
Connection: keep-alive
Vary: Accept-Encoding
Cache-Control: no-cache

{"status_code": 404, "message": "user lwcolton@gmail.com not found"}(pyraml) Coltons-MacBook-Pro:raml coltonlw$`

**Comment by nagem** [comment]
The real source of this problem is allowing users through our authentication step in `base.RequestHandler` marked as a public request and waiting to check authorization to varying levels of time. Some handlers boot public requests immediately while some allow the request to reach telling errors (such as the 404 colton linked above). Most wait until right before the db lookup (like `ContainerHandler`). 

After an offline discussion with @coltonlw, we agreed that the idea of public requests should be revisited and at the very least switch to a default reject format for endpoints, allowing those that should be public to opt-in. 

@gsfr interested in your perspective.

**Comment by gsfr** [comment]
Happy to see security tightened, of course, but the ability to make data public is a core feature that we cannot remove.

I could imagine duplicating the relevant routes for public data under a `/pub` prefix, and all non-pub routes are locked down to authenticated users only.

Would such an approach address this issue?

**Comment by coltonlw** [comment]
Sure, that would work, as it would require public endpoints to be explicitly defined as public by placing them under the /pub prefix.  The issue is right now all endpoints are public unless explicitly made private by the code in the view.  I'm suggesting we reverse that default behavior, so all endpoints are private unless the code declares them public.  This still allows us to have the same public endpoints we do now, it just prevents scenarios where code in private views forgets to require login as the first step.  /pub prefix is one way to do this, another common way would be adding code to BaseHandler that 400's any unauthenticated request, unless for example the handler class has a "public" attribute set to True.

**Comment by coltonlw** [comment]
@gsfr Are you able to help me compile a list of endpoints which need to allow public access at this time?
