### ISSUE TITLE
Add search status endpoint

### ISSUE THREAD

**Issue by kofalt** [scitran/core#396]
A public endpoint that always returns 200, providing information about the current status of our elastic search component. Used to know if search is:
1. Healthy - ready for queries
2. Indexing - search results may be incomplete
3. Error - connection failed or other problem

Intention is that you could poll `/status/search` or whatever until healthy is returned.

``` js
{
    status: "healthy | indexing | error"
}
```

May be relevant to @ryansanford. ~~Blocker for NIH work.~~

**Comment by gsfr** [comment]
Given that this is no longer a blocker for NIH work, does anyone actually need this right now?

**Comment by nagem** [comment]
@gsfr I do not believe so, no. I agree it would be a useful feature to have at some point, though.
