### ISSUE TITLE
Access logging

### ISSUE THREAD

**Issue by gsfr** [scitran/core#397]
In our effort to becoming HIPPA compliant, we have to start logging user access to data.

In a first iteration, let's implement logging of the following "view" events:
- [ ] bulk file download
- [ ] individual file download
- [ ] file viewing
- [ ] retrieval of subject information

To keep us from having to log each session that is returned by session list queries, we should consider stripping non-essential information from those session lists, including the subject information.

I'm inclined to start with logging to a rotating log file, not the DB.

Open to hearing further thoughts and suggestions.

**Comment by ryansanford** [comment]
@gsfr 
Can we get a link to the relevant HIPAA guideline we are attempting to address?

**Comment by kofalt** [comment]
To get things started, here's roughly what I had in mind last time we discussed this.

Append-only collection called `events` with format:

```js
{
    "originator": "", // user or device ID. 
    "originator_ip": "127.0.0.1",
    "timestamp": "",

    "action": "", // dot-namespaced enum, following github's audit log convention.
    // examples: team.create, team.destroy

    "target": "acquisition/3" // target container, if applicable, in URL-ish format
}
```

Open questions:

1. Is this sufficient to log every action we need? Does `target` need to be an array?
1. Decide if an event is created before or after an action is taken. I'd say before, and we document that the event log is susceptible to false positives. Alternative is false negatives.

**Comment by ryansanford** [comment]
Are there search requirements? Search capability was a big deal in the patient/clinical space. Things like "Get all history for this study." and "Get all records for user X on day Y." and "Get all delete actions for the last 7 days."

**Comment by nagem** [comment]
If it fulfills all the requirements for what we need to log, I was thinking a simple decorator we can add to handler methods that logs uid/drone id, ip, the "action" (method, our own notation, etc), the query params and the request body that is invoked after the handler method completes would work. Something like this:

```
@log_decorator(action='user.get') # Here we are using our own notation
def get(self, _id):
    ...
```

**Comment by gsfr** [comment]
Thanks everyone for the great comments and questions.

@ryansanford Please obtain specific HIPAA info from resident HIPAA expert @inijim. Following his lead here. +1 on search capability.

@kofalt +1 on newline-delimited JSON. +1 on false positive over false negatives. -1 on making `target` an array. I'd prefer logging each target separately, even for bulk downloads. Makes searching easier, for instance.

@nagem +1 on using a decorator. +1 on a rich set of attributes.

Also, generally, +1 on using the DB for storage. This will likely impact our system requirements. We may also need a scheme for archiving old logging data, say, >2 years, into files in order to prevent DB bloat.
