### ISSUE TITLE
Review skipped abao tests

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#404]
We are skipping some abao tests for various reasons, this issue tracks those tests so we can begin making the changes necessary to enable them.

Skipped tests are listed here: https://github.com/scitran/core/blob/master/test/integration_tests/abao/abao_test_hooks.js

**Comment by nagem** [comment]
According to [this comment](https://github.com/cybertk/abao/issues/149#issuecomment-226778697), we will not be able to send file form data using abao, or at least not yet. 

Unfortunately since we expect the upload calls to be of this type, we cannot test metadata only, either.

**Comment by coltonlw** [comment]
The majority of the remaining skipped tests are for Jobs, which just need a workflow test for creating a project and session and uploading data, so those objects are available in the API to enable creating a test job.  I'm working on that in a feature branch so I'll steal this issue.
