### ISSUE TITLE
Documentation for scitran/core

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#407]
- [x] Clearly outline difference between scitran.github.io  and scitran.github.io/core
- [x] Decide what to use or not use the github project wiki for
- [ ] Define index layout for scitran.github.io/core
- [x] Find home for coding standards and new API resource creation process
- [ ] Document work items for frontend developers to style the docs and API console
- [ ] When styling the API console, adhere to the license paying special attention to section 3.3. See   https://github.com/scitran/core/issues/415#issuecomment-241008204

**Comment by coltonlw** [comment]
@gsfr Can you help answer some of the questions above in terms of the two different github pages sites, the project wiki, and the layout of the different github pages?

**Comment by gsfr** [comment]
Here is my humble opinion:

- scitran.github.io should provide an overview of all active repos, as well as a mission statement. I'm thinking, single page. It should link out to *our friends and valued contributors at Flywheel*, and Flywheel can link back to there.

- The individual repo pages provide more detailed information and documentation.

- For now, I would use the wiki sparingly, if at all. The data model is in there for convenience. Open to suggestions.

- Brian put a lot of details into the [scitran/client wiki](https://github.com/scitran/client/wiki). Some of that should probably move to core or even to scitran.github.io and get referenced there.

- In core, I would start with a few markdown files: /CONTRIBUTING.md, /TESTING.md, and maybe raml/README.md. /README.md should be the overall entry point, appropriately referencing the other .md files.

**Comment by coltonlw** [comment]
@gsfr You can see what I've done so far in the README of master:  https://github.com/scitran/core
