### ISSUE TITLE
Remove insecure mode 

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#410]
Right now we run our integration tests in "insecure" mode which allows any user to impersonate any other user and also to gain root privileges without actual authorization.  To properly verify permissions we will need to run in "secure" mode and use different test accounts for different roles.  My opinion is that insecure mode should be removed altogether, the same thing can be accomplished simply by adding a test user with root permissions, and that doesn't leave us open to the pitfall where a production instance somehow gets insecure mode turned on.

https://github.com/scitran/core/blob/master/api/base.py#L26

https://github.com/scitran/core/blob/master/api/base.py#L56

https://github.com/scitran/core/blob/master/test/docker-compose.yml#L29

**Comment by coltonlw** [comment]
Also remove debug links

**Comment by ryansanford** [comment]
@coltonlw Check with Imad before proceeding. He has expressed appreciation in the past with the debug links. See if there's a way to accommodate his use case in a post-insecure-mode world.
