### ISSUE TITLE
Add API key support for devices

### ISSUE THREAD

**Issue by nagem** [scitran/core#413]

**Comment by kofalt** [comment]
Based on conversation out-of-band:

* Superuser can add, regenerate device keys
* Presumably, it'd be `device/<id>/key` or something
* Still only one key per identity, still no permission mask
* Shared-secret authentication would remain for now to be an additive change

This would be helpful for engine SDK usage :+1: 
The infrastructure would add an "engine" device, then create a key, then hand it to me.
