### ISSUE TITLE
Review API Console License

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#415]
We need to review the license for the mulesoft API console, since we are hosting it in the gh-pages branch of our repo

@ryansanford gunnar said you could help with that

https://github.com/scitran/core/blob/gh-pages/docs/api/api-console/LICENSE

**Comment by ryansanford** [comment]
As long as we don't make modifications, and keep the LICENSE in place, this will be ok to use. If we make changes to CSS down the line, adherence to section 3.3 will be important, beyond the usual OSS license considerations.
