### ISSUE TITLE
Extend the API to support label uploads from users

### ISSUE THREAD

**Issue by rentzso** [scitran/core#423]
Label uploads are only available to drone requests.
However, the [organizer](https://github.com/scitran/organizer) should use that route to upload user data.
A possible solutions is to provide a route to retrieve a drone API key for normal users (related to #413 I guess).
@nagem @gsfr I would like to know your thoughts about this.
Thanks!

**Comment by nagem** [comment]
Our error message erroneously reads `uploads must be from an authorized drone` but really it's just super_user that is required for the request (most likely to minimize permissions checking on upload). @gsfr might have a better idea on who the typical user for the organizer will be and if it is possible they don't have site admin rights.

A drone API key will give them the same rights as super_user so it wouldn't really make sense to generate drone API keys for users, and depending on implementation of #413 we'd lose user context.

**Comment by nagem** [comment]
If indeed we do need to support users that are not site admins using the organizer, we'll have to add permissions checks to the upload endpoints.

**Comment by gsfr** [comment]
Anyone should be able to upload data, using tools like the Organizer or folder sniper. Permissions checks seem inevitable.

**Comment by nagem** [comment]
We'd probably want to check permissions before the user sends us any files, so would upload move to a two-step transaction like download? Intent to upload generates an upload ticket?

**Comment by gsfr** [comment]
Probably a good idea.  Uploading for hours just to have every file denied would make for a very poor user experience. Not necessary right away, though. A standard permissions check might get us launched faster and won't require refactoring on the Organizer or sniper side.

**Comment by nagem** [comment]
For the `api/upload/*` endpoint, we ensure the hierarchy exists/create it during the `check()` phase of the placer. We could add permchecks there initially so at least you'll get a `403` earlier in the process.
