### ISSUE TITLE
Incorrectly setting __config_persisted

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#439]
In config.py we incorrectly set __config_persisted, resulting in database initialization and config write happening twice.  The following snippet is from [config.py](https://github.com/scitran/core/blob/master/api/config.py#L237):  

``` python
r = db.singletons.replace_one({'_id': 'config'}, __config, upsert=True)
__config_persisted = bool(r.modified_count)
```

on upsert, modified_count will be equal to 0.  The mongo response object has a property called "upserted_id" which will have the id of the upserted document.  Thus the first time we save the config, r.modified_count is 0 and when we cast that to a boolean it returns False, meaning __config_persisted is set to False.

**Comment by gsfr** [comment]
Nice catch, @coltonlw.

Seems to me that we don't actually care whether an insert or an update took place. Since any problem with the Mongo operation would raise an exception and stop the local control flow, we should be fine simply setting `__config_persisted` to `True`. Right?

**Comment by coltonlw** [comment]
Yeap that sounds correct to me
