### ISSUE TITLE
failed to open python file bin/api.wsgi in core/docker examples

### ISSUE THREAD

**Issue by landge** [scitran/core#440]
Hi,
I would like to test scitran and tried following your examples in core/docker readme.md. But I
get stuck with an uwsgi error msg (docker on debian): 

```
*** Operational MODE: preforking+threaded ***
added code/data to pythonpath.
failed to open python file bin/api.wsgi
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
```

I don't understand how all the parts are fitting together. I know this seems to be an uswgi configuration issue, but isn't everything set up correctly by the docker run command in the docker/examples? I'm new to docker and uswgi.... so any help is very much appreciated!

**Comment by ryansanford** [comment]
@landge 
I assume you are operating off of a fresh clone of the master branch? Are all the files in your local clone globally readable? Were the example commands are executed from the root of the repo, and not the docker subdirectory?

The command `docker inspect scitran-core` will display details on  the docker container setup using the example. In the "Mounts" section, look for an entry matching `"Destination": "/var/scitran/data"` and confirm the "Source" immediately above it is the root of this repo. The intent of this mount is so code changes will be reflected immediately within the running container.

While the docker container is running, you could also execute `docker exec -it scitran-core bash` to get an operational shell within the container to inspect things from within. If you do this, confirm the existence and permissions of /var/scitran/code/api/bin/api.wsgi.

**Comment by landge** [comment]
Thanks Ryan,

I worked with an docker image form docker hub and did not pay attention to
file localisation. I'll check out your comments and
see how far I get.

Thank you once more!

**Comment by landge** [comment]
I executed the example commands from within the docker directory. That caused the errors...
Thanks!

**Comment by ryansanford** [comment]
Glad to hear.
