### ISSUE TITLE
Bring gh-pages docs into mater branch

### ISSUE THREAD

**Issue by gsfr** [scitran/core#444]
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch

**Comment by coltonlw** [comment]
docs/ folder is in master, just need you to update the settings @gsfr

**Comment by gsfr** [comment]
Settings updated, but getting a 404 from the docs now.

**Comment by coltonlw** [comment]
Fixed the directory structure, it works now

**Comment by gsfr** [comment]
Safe to delete the gh-pages branch now?

**Comment by coltonlw** [comment]
Go for it
