### ISSUE TITLE
handle_exception never used

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#452]
I can't find anywhere in the code that we are actually calling the handle_exception function from base.py

https://github.com/scitran/core/blob/master/api/base.py#L263

```
(scitran) Coltons-MacBook-Pro:core coltonlw$ grep -r "handle_exception" api/
api//base.py:    def handle_exception(self, exception, debug):
(scitran) Coltons-MacBook-Pro:core coltonlw$
```

**Comment by nagem** [comment]
http://webapp2.readthedocs.io/en/latest/guide/exceptions.html#exceptions-in-handlers

It's a webapp2 `RequestHandler` method.
