### ISSUE TITLE
CI Change followup

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#458]
These will get broken into separate issues.
- [x] Remove test/Dockerfile -- #474
- [x] Trigger docker image auto-build ala reaper (@gsfr)
- [ ] Block running service as root within docker entrypoint script
- [ ] Update Image to 16.04 or python 2.7 standard/slim/alpine (@gsfr) -- #786 
- [ ] Switch to travis-docker build & evaluate need for ubuntu install script (@gsfr)
- [x] Remove insecure mode (@coltonlw)
- [x] Remove debug links (@coltonlw)

**Comment by gsfr** [comment]
Can we also delete `bin/load_users_drone_secret.py`?

**Comment by ryansanford** [comment]
@gsfr We can't delete it today, as that is used for the automated installation of accounts. I'd prefer for scitran/core to continue to offer this utility script that uses the REST API for user/group creation.

**Comment by gsfr** [comment]
Thanks, @ryansanford. Makes sense. For now. Eventually, I'd like to drop the drone secret functionality altogether.

Separately, I have updated the checklist above with assignments. It'd be great if someone would claim the last unassigned item, although that one should probably be done last.
