### ISSUE TITLE
Rework OAuth flow, use library

### ISSUE THREAD

**Issue by nagem** [scitran/core#459]

**Comment by nagem** [comment]
Addressed as part of https://github.com/scitran/core/pull/652

**Comment by kofalt** [comment]
Did you end up deciding to not use an OAuth library?
I don't have a huge opinion on it, just curious how it turned out.

**Comment by nagem** [comment]
Nah, they didn't really provide anything useful. They really just set up your request for you but LDAP and WeChat are so different from the norm that it didn't seem like we'd get much usefulness out of using one.
