### ISSUE TITLE
Input / Output schemas and data validation for Jobs resource

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#465]
Jobs resource currently does no input validation.  Some schemas have been added in the RAML.  these must be finalized, examples finalized also.  Lastly, the Jobs resource must be modified to validate the input data using the newly created schemas

@ryansanford

**Comment by kofalt** [comment]
IMO, the best way to satisfy this would be to use the `validators.validate_data` function to check a blob of json against a schema without changing all the code to be decorators & etc. Example from `placers.py`:

```python
validators.validate_data(self.metadata, 'file.json', 'input', 'POST', optional=True)
```

**Comment by coltonlw** [comment]
@kofalt validate_data still uses the decorators underneath.  Talking to Megan we'd like to add a public function to the validators module that would retrieve a schema and validate data against it, without using decorators or manipulating the jsonschema's   I understand your concern is with the decorators and the logic implemented inside of them, so hopefully you find this proposal an even better solution.  

Blocked by #480

**Comment by kofalt** [comment]
That sounds great to me!
