### ISSUE TITLE
Allow "version" to be set when uploading analysis

### ISSUE THREAD

**Issue by lmperry** [scitran/core#486]
Currently I can't specify the `version` of a given analysis when uploading an analysis via the scitran client CLI. Let's modify the analysis input schema to allow the version of the analysis to be set as well. 

Bonus: Allowing `tags` to be set would be great too. 

https://github.com/scitran/core/blob/master/raml/schemas/input/analysis.json#L1-L26

**Comment by kofalt** [comment]
My guess is this was for the version of a gear that ran the job! These days, we have a `job` key, which in turn references a gear document, which in turn references the version.

I'm closing this, but feel free to re-open if you don't think that qualifies for what you need.
