### ISSUE TITLE
Improve speed / caching of run-tests-docker.sh

### ISSUE THREAD

**Issue by kofalt** [scitran/core#493]
`run-tests-docker.sh` works great, but does a bunch of pip/npm/docker cycling on each run.

Since this is something to run iteratively, it would be nice to jump straight to the actual tests, using a clean & already-built set of containers if they've been built before.

**Comment by coltonlw** [comment]
@ryansanford I'm going to investigate this see how much of the native testing can use the docker test script instead, nice work you did there.

**Comment by ryansanford** [comment]
@kofalt I believe PR #500 resolved this issue. Can you confirm?

**Comment by kofalt** [comment]
Yes, it seems to work pretty well now :)
