### ISSUE TITLE
Error listing collection curators

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#507]
I am unable to hit /api/collections/curators to list collection curators   I believe the issue is in CollectionHandler.curators where we call self.get_all,    get_all doesn't take any arguments (besides self)

Relevant lines:

```
uwsgi_1           |   File "./api/handlers/collectionshandler.py", line 131, in curators
uwsgi_1           |     curator_ids = list(set((c['curator'] for c in self.get_all('collections'))))
uwsgi_1           | TypeError: get_all() takes exactly 1 argument (2 given)
```

Full traceback:

```
:DEBU from None coltonlw@flywheel.io GET /api/collections/curators {} request_id=b1ff883d-1474306455
uwsgi_1           | 2016-09-19 17:34:15      scitran.api                  base.py   286:ERRO Traceback (most recent call last):
uwsgi_1           |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
uwsgi_1           |     return method(*args, **kwargs)
uwsgi_1           |   File "./api/handlers/collectionshandler.py", line 131, in curators
uwsgi_1           |     curator_ids = list(set((c['curator'] for c in self.get_all('collections'))))
uwsgi_1           | TypeError: get_all() takes exactly 1 argument (2 given)
uwsgi_1           |  request_id=b1ff883d-1474306455
uwsgi_1           | [pid: 17|app: 0|req: 36/59] 192.168.99.1 () {34 vars in 472 bytes} [Mon Sep 19 17:34:15 2016] GET /api/collections/curators => generated 79 bytes in 8 msecs (HTTP/1.1 500) 3 headers in 130 bytes (2 switches on core 0)
```

@ryansanford Assigning you to put this in the work queue if desired

**Comment by coltonlw** [comment]
@rentzso I see you added this endpoint, can you explain what it's for and if we should fix or remove it?  

1e42681b (Renzo Frigato   2015-10-06 10:50:37 -0700 130)     def curators(self):

**Comment by rentzso** [comment]
This was used by the previous version of the UI.
I wouldn't remove it as the fix should be straightforward.

**Comment by coltonlw** [comment]
@rentzso thank you

**Comment by coltonlw** [comment]
@rentzso Would the fix be just to remove the "collections" argument, my guess is previously we were calling the get_all method of ContainerHandler, but now get_all is defined on CollectionsHandler?

**Comment by rentzso** [comment]
Yes, that should work. Trying to think if there is something I am missing there, but I don't think so.

Good catch, by the way!

**Comment by coltonlw** [comment]
@rentzso I was a little off, get_all wasn't a new method of CollectionHandler, we changed it's signature in this commit https://github.com/scitran/core/commit/f4da8b4e54bda1232a472e927aa189f3602ca816/?diff=split#diff-83d2b08159658cfe13794fe5e54eb197L101, Megan removed the cont_name argument because it was unused in the function.  So a one-line fix to the calling function curators which I'll make in my feature branch along with the test for it.  Thanks!
