### ISSUE TITLE
Empty input document added to /jobs/next output

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#513]
Example (notice empty document in "inputs" array):

``` json
{
    "request": {
        "inputs": [
            {},
            {
                "type": "scitran",
                "uri": "/jobs/57e4299174aff90167ebca62/config.json",
                "location": "/flywheel/v0"
            },
            {
                "type": "scitran",
                "uri": "/acquisitions/57e4299074aff90167ebca5e/files/1_1_dicom.zip",
                "location": "/flywheel/v0/input/dicom"
            }
        ],
        "target": {
            "command": [
                "bash",
                "-c",
                "rm -rf output; mkdir -p output; ./run; echo \"Exit was $?\""
            ],
            "env": {
                "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            },
            "dir": "/flywheel/v0"
        },
        "outputs": [
            {
                "type": "scitran",
                "uri": "/engine?level=acquisition&id=57e4299074aff90167ebca5e&job=57e4299174aff90167ebca62",
                "location": "/flywheel/v0/output"
            }
        ]
    }
}
```

Build output when empty input item is not allowed:
https://travis-ci.org/scitran/core/builds/162012945

Body of request used to add this job:

``` json
{
    "gear": "dcm_convert",
    "inputs": {
        "dicom": {
            "type": "acquisition",
            "id": "{{test-acquisition-id}}",
            "name" : "1_1_dicom.zip"
        }
    },
    "destination": {
        "type": "acquisition",
        "id": "{{test-acquisition-id}}"
    },
    "tags": [
        "ad-hoc"
    ]
}
```

**Comment by coltonlw** [comment]
@ryansanford this is a bug can you help me prioritize it in the work queue

**Comment by ryansanford** [comment]
@kofalt Is this empty input document, or its removal via a fix, risky from the perspective of the engine?

@coltonlw Assuming risk is low, my preference is to put this towards the top so details aren't lost/forgotten.

**Comment by coltonlw** [comment]
This might be caused by the job added using the example input from the RAML, which has an acquisition ID that doesn't exist.

```json
{
    "gear": "dcm_convert",
    "inputs": {
        "dicom": {
            "type": "acquisition",
            "id": "573c9e6a844eac7fc01747cd",
            "name" : "1_1_dicom.zip"
        }
    },
    "destination": {
        "type": "acquisition",
        "id": "573c9e6a844eac7fc01747cd"
    },
    "tags": [
        "ad-hoc"
    ]
}
```

**Comment by coltonlw** [comment]
@ryansanford this is blocking merging api-spec-containers because the response from this endpoint does not validate against the output jsonschema during testing

**Comment by ryansanford** [comment]
@coltonlw Was it confirmed whether the empty array item is related to the non-existant acquisition id? Please identify root cause, and propose a fix.

**Comment by coltonlw** [comment]
generate_request() from jobs.py is what creates the request sub-document.  It appends the "input" property from the gear document for the job to the inputs array.  

https://github.com/scitran/core/blob/master/api/jobs/jobs.py#L194

In the test-case gear we set the "input" property to an empty object which is what's causing this (at the very end of the line linked to below)

https://github.com/scitran/core/blob/master/test/integration_tests/postman/integration_tests.postman_collection#L332

**Comment by ryansanford** [comment]
@coltonlw I don't think that `input` object belongs on the POST gears endpoint. Our infrastructure certainly doesn't provide that when registering gears. 

I think there's 2 action items.
1. Remove that `input` object causing this behavior on `jobs/next`. This should unblock the merging of api-spec-containers?
2. Improve core to fail adding invalid gears that can break downstream functionality, or allow unstructured objects like this and protect downstream functionality.

**Comment by coltonlw** [comment]
@ryansanford Can you explain more what you mean that the "input" object does not belong?  According the code in generate_request() which I linked to we expect the gear to have a property called "input".  Also @kofalt was the one who added the postman test for creating the test case gear, maybe he can explain what the input property of the gear is for

**Comment by ryansanford** [comment]
I was wrong, the `input` object does belong on the POST gears endpoint for adding a gear, and should be required with the members `location` `type` and `uri`.

**Comment by coltonlw** [comment]
Thanks @ryansanford 👍 

@kofalt Should I just add some dummy values to the test case gear?

**Comment by kofalt** [comment]
@coltonlw That would probably work, eys

**Comment by coltonlw** [comment]
@ryansanford is "vu" also a required property of the input object?

**Comment by coltonlw** [comment]
@ryansanford @kofalt I guess the other input documents do not have the "vu" property.  I am also curious about the "type" property, in the example Ryan sent me it was "http", some of the other "input" documents from the response have this set to "scitran"
What does it mean if the input type is "scitran" and is this a good jsonschema snippet for that property?

           "type":{"enum":["http", "scitran"]}

**Comment by ryansanford** [comment]
`vu` Is not required for gears/{id} or jobs/next.

I would advocate for minimal schema validation of POST to gears/{id} today, existence check only, since it is likely changing soon related to the gear exchange integration.

**Comment by ryansanford** [comment]
This issue has been resolved.
