### ISSUE TITLE
Files array on subject input broken

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#524]
When creating a new session one of the properties of the session is "subject".  One of the properties of subject is the "files" array.  Specifying a value for the files array causes a 500 error because there is no code that adds the "created" and "modified" properties to each document in the files array, which are required by the mongo schema for files, so validation fails when saving to the database

Session document used as POST body:

``` json
  {
    "subject": {
      "code": "test-subject-1",
      "files":[
        {"name":"test-file"}
      ]
    },
    "label": "test-session-1",
    "project": "57f3f59afc12650027c58a0f",
    "public": false
  }
```

Log: 

```
→ Create test-session-1
  POST http://localhost:8081/api/sessions?root=true  2016-10-04 18:31:54      scitran.api                  base.py   100:INFO Initialized request request_id=85350149-1475605914
2016-10-04 18:31:54      scitran.api                  base.py   298:DEBU from None admin@user.com POST /api/sessions {u'root': u'true'} request_id=85350149-1475605914
2016-10-04 18:31:54      scitran.api      containerhandler.py   312:DEBU {u'project': u'57f3f59afc12650027c58a0f', u'label': u'test-session-1', u'public': False, u'subject': {u'files': [{u'name': u'test-file'}], u'code': u'test-subject-1'}}
2016-10-04 18:31:54      scitran.api            validators.py    61:DEBU {'group': u'test-group', 'created': datetime.datetime(2016, 10, 4, 18, 31, 54, 427491), 'modified': datetime.datetime(2016, 10, 4, 18, 31, 54, 427491), u'label': u'test-session-1', u'project': ObjectId('57f3f59afc12650027c58a0f'), u'subject': {u'files': [{u'name': u'test-file'}], u'code': u'test-subject-1', '_id': ObjectId('57f3f59afc12650027c58a10')}, u'public': False, 'permissions': [{u'access': u'admin', u'_id': u'admin@user.com', u'site': u'local'}]}
2016-10-04 18:31:54      scitran.api                  base.py   288:ERRO Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "./api/handlers/containerhandler.py", line 340, in post
    result = mongo_validator(permchecker(self.storage.exec_op))('POST', payload=payload)
  File "./api/validators.py", line 71, in validator
    raise DBValidationException(str(e))
DBValidationException: u'created' is a required property

Failed validating u'required' in schema[u'properties'][u'subject'][u'properties'][u'files'][u'items']:
    {u'$schema': u'http://json-schema.org/draft-04/schema#',
     u'additionalProperties': False,
     u'key_fields': [u'name'],
     u'properties': {u'created': {},
                     u'hash': {u'type': u'string'},
                     u'instrument': {u'type': u'string'},
                     u'measurements': {u'items': {u'type': u'string'},
                                       u'type': u'array',
                                       u'uniqueItems': True},
                     u'metadata': {u'type': u'object'},
                     u'mimetype': {u'type': u'string'},
                     u'modified': {},
                     u'name': {u'type': u'string'},
                     u'size': {u'type': u'integer'},
                     u'tags': {u'items': {u'type': u'string'},
                               u'type': u'array',
                               u'uniqueItems': True},
                     u'type': {u'type': u'string'}},
     u'required': [u'name', u'created', u'modified', u'size', u'hash'],
     u'type': u'object'}

On instance[u'subject'][u'files'][0]:
    {u'name': u'test-file'}
 request_id=85350149-1475605914
[500 Internal Server Error, 1.42KB, 47ms]
127.0.0.1 - - [04/Oct/2016:18:31:54 +0000] "POST /api/sessions?root=true HTTP/1.1" 500 1459 "-" "PostmanRuntime/2.4.4" request_id=85350149-1475605914
  1⠄ Status code is 200
  ✓  Response time is less than 200ms
```

**Comment by coltonlw** [comment]
@ryansanford this is a blocker for api-spec-containers

**Comment by nagem** [comment]
Just a few things that might explain this:

1. The `files` array should never be in an input schema for a container (projects/sessions/acquisitions). The lists are modified through `api/<cont_name>/<cont_id>/<list_name>` (but files can also be modified through one of the upload endpoints).
2. Subject-level files are in an in-flux state. They were added to support the BIDS format and more work needs to be done to support them fully. See #453 for a bit more info.

**Comment by nagem** [comment]
I see that `files` is in the current input schema, that is the actual bug 😄.

**Comment by coltonlw** [comment]
Did you add it there to support update behavior on PUT where we use the same schema as new object / POST ?

**Comment by nagem** [comment]
I'm not sure why it was added, but adding subject files is only supported via the `api/upload` endpoint.

**Comment by coltonlw** [comment]
Thing number 1 from your previous comment led me to believe files array could be edited via one of the api/<cont_name>/<cont_id>/<list_name>  routes, are you saying that's not true?

https://github.com/scitran/core/commit/5b2e8c601c077ea9b998af47bde008476ce9016d#diff-887dbc1139435dcd879269c42e817e21L15

**Comment by nagem** [comment]
Correct. I meant input schema in the old style, where we had input and mongo. It is part of the storage/output schema but never part of the input/update schema.

**Comment by coltonlw** [comment]
What are storage/output schemas vs input/update schemas?

**Comment by nagem** [comment]
I was attempting to describe the new organization of schemas you've proposed with the rework:

https://github.com/scitran/core/tree/api-spec-containers/raml/schemas/output

vs

https://github.com/scitran/core/tree/api-spec-containers/raml/schemas/input

I used the word "storage" to mean schemas that more closely represent how the data is stored, which is usually observed through output from the API (for example those that include created/modified timestamps and array fields). Sorry if that added to the confusion.

**Comment by coltonlw** [comment]
What I'm really trying to ask is why are you referring to storage/output schemas as one unit and input/update schemas as another?    There were no output schemas until I began creating them.  The output schemas I've created were made to share definitions with the input schemas, and are completely separate from the mongo schemas, although later the mongo schemas could be updated to share definitions with input and output schemas as well.    

I don't understand how that relates to your comment number 1, not sure that matters though I think what you're telling me is you accidentally added the files array to the input schema for subjects or don't remember why you did, and so we can just remove it?  I linked to the commit in case that helps

**Comment by nagem** [comment]
The other information is distracting from the heart of the issue, we can have a conversation offline to make it more clear. 

For now - to close this issue, remove the "files" key from the "subject" key in the session input schema.

**Comment by ryansanford** [comment]
@coltonlw Priority for the RAML spec blocking issues is below session templates, and regression bugs blocking the cut of the next release. Thanks for scoping this out, and the work on identifying a resolution.

@nagem Thanks for adding context and info on this issue to help unblock @coltonlw.
