### ISSUE TITLE
Handle subject id properly when subject code changes

### ISSUE THREAD

**Issue by nagem** [scitran/core#528]
Currently if you add a new subject with the same code as an existing subject in the project, it will have the same ID. We do not properly handle a change to an existing subject's code.

**Comment by nagem** [comment]
See https://github.com/scitran/core/issues/484

**Comment by ryansanford** [comment]
@nagem I would expect an edit to Subject Code to behave the same as if a new session was being added with the resulting Subject Code. 

What is the function of the Subject ID, beyond being used as a unique key for project reports?

**Comment by nagem** [comment]
Nothing yet. It was added with the intention of being better prepared when we (possibly) move to having a subject-level container. There was also the idea floating around that a user could multi-select sessions in the UI and "mark" the session's subjects as being the same subject.

**Comment by hkethi002** [comment]
So if the subject code is changed, the subject should be given a new _id?

**Comment by nagem** [comment]
If the subject code is changed to a code that already exists in the project, it should be given that ID. Otherwise if it is unique to that project, it should be given a new id.
