### ISSUE TITLE
Runtime modification of jsonschema's forces duplication 

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#537]
validators.py  will remove the "required" keyword from a jsonschema on "update" operations.  We do this instead of having a separate schema for "new object" and "update object" operations.  Because of this, "required" must only be specified at the top-level of each input schema, preventing schemas from re-using a shared object definition where "required" is defined

https://github.com/scitran/core/blob/master/api/validators.py#L84

**Comment by kofalt** [comment]
A dumb patch might be to walk the schema, removing each instance of any `required` key, but that would likely cause its own problems.

**Comment by coltonlw** [comment]
@kofalt Indeed.  A more complete solution would be:

1) Add functionality for separate "new" and "update" schemas to validation logic,  for example in the ContainerHandler class
2) Update all CRUD functionality to use separate new and update schemas, specifying "required" in the input schema definition
3) Remove code from validators.py which modifies jsonschemas dynamically

Also during the process it would be helpful to investigate how python jsonschema library can be made to validate against a schema in the "definitions" property of a schema file.  This would remove the need for quite a few of the files in the "raml/schemas/input" directory, which only reference a definition from the definitions folder and add the "required" keyword at the top level.

**Comment by ryansanford** [comment]
This is causing unnecessary complexity for creating the json schemas.

**Comment by ryansanford** [comment]
@coltonlw 
I'm assigning this to you for the upcoming sprint. Review proposed changed with @nagem before proceeding.

**Comment by ryansanford** [comment]
Reviewed the effort/risk with @coltonlw and choosing to not tackle this next sprint. Cost is not worth the benefit at this moment.
