### ISSUE TITLE
Add endpoint that does not require file upload if the file already exists in the CAS

### ISSUE THREAD

**Issue by nagem** [scitran/core#539]
If the file can be identified as already existing in the CAS via hash, there should be a workflow that allows the user to "attach" a file to a container without uploading the file itself.

Notes:
- only allow the user to access files in the CAS that are attached to a container the user already has access to
- possibly add index of file hashes to easily search for other places this file is attached (for permissions check)

**Comment by gsfr** [comment]
Thanks, @nagem. This is relevant for the NIH raw data upload flow. Please work with @ryansanford and @kofalt to prioritize.

**Comment by kofalt** [comment]
My thoughts from previous offline discussion: this feature should only work if we have a hash-match among files the user can access. This prevents an attacker from learning which files are present.

**Comment by nagem** [comment]
Thanks for noting that, @kofalt. I have a few other notes as well that I'll update the ticket with soon.

**Comment by gsfr** [comment]
For the given NIH use case, the implementation can likely be limited to drone uploads, avoiding the noted security concerns.

**Comment by nagem** [comment]
Plans to remove the CAS make this ticket obsolete.
