### ISSUE TITLE
Wrong type for file size

### ISSUE THREAD

**Issue by kofalt** [scitran/core#544]
On dev.flywheel.io, there are several instances of floating-point file sizes: `989633.0`.
This blocks using the CLI with any instance that has this error :disappointed: 

* [ ] Add a database migration that corrects any file size float to int
* [ ] Identify root cause (if one still exists) and fix

**Comment by ryansanford** [comment]
@nagem I assigned this to the next sprint assuming low effort. Let me know if you expect effort to be higher.

**Comment by kofalt** [comment]
Resolved by #558
