### ISSUE TITLE
Change satisfies_template to does_not_satisfy_template

### ISSUE THREAD

**Issue by dpuccetti** [scitran/core#561]
This value is currently only guaranteed to be set when it's value is false, which means that true for the UI is either true or undefined.  This makes for awkward comparisons.  Changing the value to always be set when the value is true would simplify comparisons in the UI.

Always returning a value (true/false) for satisfies_template would also work.

**Comment by dpuccetti** [comment]
Related frontend issue: https://github.com/flywheel-io/frontend/issues/666

**Comment by ryansanford** [comment]
@nagem We closed the dependent frontend ticket. Ok to close this one?
