### ISSUE TITLE
Fix reporting typo/bug when all subjects have no sex or age

### ISSUE THREAD

**Issue by nagem** [scitran/core#565]
During @coltonlw's testing he unearthed a typo here:
https://github.com/scitran/core/blob/master/api/handlers/reporthandler.py#L61

Also, if all the subjects that have an `_id` do not have the `sex` or `age` field, the aggregations will fail.

**Comment by shreab373** [comment]
hello, i'm new to open source, can i solve this? could you guide me?

**Comment by nagem** [comment]
This was fixed as part of the integration testing overhaul.
