### ISSUE TITLE
Uploading by label returns empty result

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#566]
When sending a POST to /api/upload/label which creates a new project/session/acquisition hierarchy, the response body is an empty list even though objects were created

**Comment by nagem** [comment]
As @coltonlw talked about offline, the upload endpoints only return a list of file objects created, so it is behaving "as designed". It would be nice if endpoints that create/find hierarchy (label/uid/packfile upload) returned at least the `_id` fields of the hierarchy they found/created.
