### ISSUE TITLE
Jobs are not spawned from files uploaded by UIDPlacer

### ISSUE THREAD

**Issue by kofalt** [scitran/core#579]
The UIDPlacer has [job creation](https://github.com/scitran/core/blob/d47552405ab1a92a1e3c3f67f053c17627f28fcf/api/placer.py#L186-L192) commented out. When this is re-activated, be sure to pass it the modified (saved) container as per offline discussion!

**Comment by nagem** [comment]
After reviewing that segment again, we shouldn't be spawning jobs on subject files. I'll remove the commented out code and add a comment for clarity.
