### ISSUE TITLE
Validate UIDs in roles and permissions

### ISSUE THREAD

**Issue by gsfr** [scitran/core#58]
At least for the local site, we should only allow new roles and permissions for actual user IDs.

**Comment by kofalt** [comment]
Can you elaborate? This is on the Bali milestone but not assigned to anyone

**Comment by gsfr** [comment]
> Am I correct in thinking that you're asking for foreign-key-like behaviour here?

Correct.

@rentzso is investigating scope. Will move to post-bali as appropriate.

**Comment by rentzso** [comment]
removed from the Bali milestone

**Comment by rentzso** [comment]
as part of this issue we will also change the `DELETE api/user/userid` so that it will only disable the user instead of deleting it.

**Comment by gsfr** [comment]
I would suggest that we error on `DELETE` and use `PUT` for setting a `disabled` flag on the user.
