### ISSUE TITLE
Allow engine metadata to update existing file data

### ISSUE THREAD

**Issue by nagem** [scitran/core#596]
Currently the only way to set file "object" metadata (the data associated with a file like `measurements`, `modality`, `info` etc) is to set this information when the file is uploaded. Some gears produce metadata about input files (for example, `measurements` information and dicom header `info`. File metadata should be able to be modified by gears. Engine metadata should never replace existing metadata on the file object. 

There are two main methods this could be implemented:

  - The schema for engine metadata remains unchanged. The metadata produced by the gear would contain the target container object and a list of file objects associated with that container. Usually this only references files being uploaded, but if a file is not included in the file form, it will be assumed that it is referencing a file already attached to the target container and that file object's metadata will be updated. 

  - The metadata for updating files will be explicitly separated from the metadata referencing the files produced by the gear, perhaps in an `updated_files` array.

**Comment by nagem** [comment]
@kofalt do you have any opinion on the implementation? I am partial to the first but let me know if we would want to be more explicit.

**Comment by kofalt** [comment]
Based on offline conversation, Megan has chosen approach one (more or less), the core will accept the current (soon-to-be-legacy) structure and backsupport the keys we're changing. I will update the gear spec to show off the new format and let Michael know about a classifier change.

**Comment by nagem** [comment]
This was implemented in https://github.com/scitran/core/pull/246
