### ISSUE TITLE
Test isolation, iteration speed, and developer QoL

### ISSUE THREAD

**Issue by kofalt** [scitran/core#600]
Quantitative: say `test <name of test>`, that single test runs in some low-single-digit number of seconds.
Qualitative: it should "feel good" to write tests.

Closing this ticket will: enable the writing of more tests, better tests, and make it feasible to do TDD :+1: 

----

Good stuff to keep:

1. Our test ecosystem boots a separate environment each time, keeping the dev environment separate. This is a big improvement over the past, where test data & example data would conflict.

1. Generated documentation is a boon to API consumers! Dan loves it.

1. The python integration tests have good infrastructural support: stateful context is dependency-injected on-demand with setup / tear-down applied per-test. Good for isolation.

1. Coverage has increased by ~40%, absolute not relative, since August. A lot of it is mainly checking http return codes, but that's still a big improvement :)

----

Challenges:

1. `test | wc -l` --> 3470, `time test` --> 50s. There's a lot of noise and it's a single stream, so it's hard to pick apart failures and identify different sections of the test plan.

1. We have ~4 tools and corresponding suites of tests, depending on how you look at them: python unit, python integration, postman, and abao. Large barrier to entry and organizational sprawl.

1. These suites of tools depend on each other: python -> postman -> abao. They are not isolated from each other and downstream suites will fail without the entire upstream suite(s) having executed.

1. Interacting with the postman test suite is an exercise in wrangling.

    a. The postman UI is pretty great, but to my knowledge, it is incapable of working directly from source code. Each branch switch or code change is an import --> edit --> export flow.

    b. The postman export format is more of a [serialized blob](https://github.com/scitran/core/blob/6b1778db993508a0fd9408f5a4494cd8bedcf012/test/integration_tests/postman/integration_tests.postman_collection#L284), making hand-edits & diff review infeasible, so it functions as sort of a binary blob in git history.

    c. The actual tests themselves are in a rather clunky [javascript syntax](https://github.com/scitran/core/blob/6b1778db993508a0fd9408f5a4494cd8bedcf012/test/integration_tests/postman/integration_tests.postman_collection#L1357), which has some strange quirks - `JSON.parse` :pensive:, can't reuse any python helper functions, and needs redundant boilerplate to function.

   d. Each postman test may rely on some or all of the tests before it, so lots of global-map setting is required to rig them all together. Iterating on the 50th test in the GUI requires running the 49 tests above it.

1. Abao tests are single requests run in arbitrary order, limiting their usefulness, and have a large [string map to function call](https://github.com/scitran/core/blob/6b1778db993508a0fd9408f5a4494cd8bedcf012/test/integration_tests/abao/abao_test_hooks.js#L320-L361) syntax.

1. A drawback of the noted upside to python-integration tests is that there's a lot of traffic to setup & tear-down each test, and the contexts required are verbose. Possible to flatten / simplify?

1. Output of the python integration tests is confused. `print` does nothing, `log.info` and `log.warn` will each conditionally show based on if that test failed. Getting information out could be simpler.

**Comment by ryansanford** [comment]
FYI -- I'm going to spin off multiple issues from this one, then close this one out after all issues that will be addressed are accounted for.
