### ISSUE TITLE
Revoke only option for CLI Key

### ISSUE THREAD

**Issue by elisapoquette** [scitran/core#610]
We should add a "Revoke" and not just "Revoke and Generate".  As a user, I should be able to have an account without a key generated.

**Comment by kofalt** [comment]
I would be happier if a user could have multiple API keys, naming and revoking them individually. That is how every notable system of that sort works: https://github.com/settings/tokens

I would also like the ability to limit key access (example: create a read-only key for a single project), but we can't always get what we want :smile: 

Ref #413, probably other initial discussion when we were designing API keys but I can't find it.

**Comment by nagem** [comment]
@kofalt all were discussed, but we went with the simplest solution first. The first request is simple, the latter would require a reworking of how permissions work in the API :).

**Comment by nagem** [comment]
I'd be happy to work on revoking, named keys and drone API keys in a followup PR to the original #413.

**Comment by elisapoquette** [comment]
Just a little bit of context, this was a casual request from Imad. If the level of effort is high, we can push back on this until there is an ask from the customer.

**Comment by nagem** [comment]
Level isn't high, a day or two at most to add names and revocation. Feel free to prioritize this ticket.

**Comment by elisapoquette** [comment]
This is definitely behind batch processing and HIPPA logging, but let's revisit at a later date.

**Comment by kofalt** [comment]
Realistically, we're not focused on this right now.
