### ISSUE TITLE
add comments/documentation for all routes

### ISSUE THREAD

**Issue by rentzso** [scitran/core#63]
Acceptance Criteria:
Close when all routes from api.py are fully documented in api.raml

EDIT by Colton:  Compare api.raml  and routes in api.py to find api resources which have not yet been added to the raml spec

**Comment by gsfr** [comment]
We will add docstrings to all http endpoints, following the [sphinxcontrib.httpdomain format](https://pythonhosted.org/sphinxcontrib-httpdomain/). From that, we will generate sphinx documentation, or possible swagger docs.

**Comment by kofalt** [comment]
A drive-by vote for swagger over sphinx since the example I was shown was so awesome: clean presentation, readable examples, support for firing an example query built in right in the web page.

**Comment by gsfr** [comment]
Actually, I'd love to go with swagger for the obvious awesomeness reasons, but we could not find an automated way to generate swagger from Python docstrings. For that reason, nothing got done so far. Yesterday we found the Sphinx thing, which finally looked like a path forward. Certainly open to suggestions.

**Comment by kofalt** [comment]
An update - thanks to #259, we now have Sphinx documentation generated and available at `/api/docs`. @ryansanford has proposed, and I agree, that any new endpoints should not be merged until they have documentation. So far that's worked out well. This ticket is now ready for implementation.

Once this ticket is complete, removing `Root.get` would be a reasonable course of action - Sphinx is generated, `Root.get` ain't. Depends on how you two - @gsfr and @rentzso - feel about this, as you're the only ones (AFAIK) who use it.

**Comment by gsfr** [comment]
Until `Root.get` is replaced with an equivalently concise and functional alternative, I'd like to retain it because I use it all the time. That said, I'd prefer to have it ported into Sphinx.

**Comment by coltonlw** [comment]
See #390 for current progress
