### ISSUE TITLE
Remove external site access code/permission logic from core

### ISSUE THREAD

**Issue by nagem** [scitran/core#638]
External site access is in a semi-maintained state. Some permissions logic requires the user's `site_id` to be checked, some doesn't. We currently do not support access from external sites. This should be removed until there is a more concentrated effort to implement this feature.

Todo:
  - remove any reference to `site` on all permissions lists on all containers
  - remove references to `site` from permissions checking logic ( most of which is in `api/auth/`)
  - remove logic from `BaseHandler()` and `centralclient.py` (or maybe all of `centralclient.py`) that references the cross-site logic

**Comment by nagem** [comment]
@ryansanford

**Comment by ryansanford** [comment]
@nagem Would the scope of this include removal of `centralclient.py`? If yes, I'd like @ambrussimon-invenshure to pick this up related to increasing code coverage efforts. Any concerns he should be aware of?
