### ISSUE TITLE
Actions that require root, made by a user with root, should not require the root flag.

### ISSUE THREAD

**Issue by kofalt** [scitran/core#657]
Example: `POST /users` will **never** work without `?root=true`!

![ippkj](https://cloud.githubusercontent.com/assets/265071/22808017/9935f61e-eeef-11e6-98a8-8e68dfbb0feb.jpg)

* [ ] `POST /users`
* [ ] More

**Comment by hkethi002** [comment]
Should posting a gear or job still require a root tag? And is superuser the same as root?

**Comment by kofalt** [comment]
Yup, superuser == root. Old naming convention holdover :)

Both the routes you mentioned can ditch the root flag.
Basically, if it's only checking for the flag we can change it.
If the endpoint does **different things** when the root flag is there, leave it alone.

For example, don't change the list endpoints: `/groups`, `/project`, etc.
Because those use the root flag to decide what data to return.

**Comment by kofalt** [comment]
I think, instead of checking `if self.superuser_request`, you can check `if self.superuser_request or self.user_is_admin`. That should work for both drones (like the engine) and users.

**Comment by hkethi002** [comment]
In the tests there is a case where a user is admin but not root, does that case not happen in practice?

**Comment by kofalt** [comment]
Can you link me to that? I'm not sure.

**Comment by hkethi002** [comment]
https://github.com/scitran/core/compare/ep-root-tag

This is in test_gears.py, line 89:
```
    # test superuser required
    r = as_admin.post('/gears/' + gear, json={'test': 'payload'})
    assert r.status_code == 403

    r = as_admin.delete('/gears/' + gear)
    assert r.status_code == 403
```
So what I ran into is that is seems that admin has root set to true when checking in handler.py for GearHandler:
```
    user = config.db.users.find_one({'_id': self.uid})
    if not self.superuser_request and not user.get('root'):
        self.abort(403, 'Request requires superuser')
```
