### ISSUE TITLE
Remove root flag and mode

### ISSUE THREAD

**Issue by kofalt** [scitran/core#658]
A follow-up to #657. Good software made for humans does not have modes.

The main purpose `root` serves today is filtering the dashboard - `view_all=true` can replace it on those endpoints.

Pinging @elisapoquette and @dpuccetti if they would like to share any thoughts.
The UI need not change per-say, but a flag would get renamed (and be used less).

**Comment by kofalt** [comment]
Relates #657, which reduced the impact of this ticket, but did not remove it entirely.

**Comment by nagem** [comment]
In a discussion with @gsfr, we hope to move in a direction of replacing the `root` flag with two distinct flags, `view_all_data` (name up for debate) and `force`. Both would require site admin. The first would work like you would expect, it would give you access to all data in the system. The second would allow permission overrides in situations like deleting containers with file attachments.

**Comment by kofalt** [comment]
SGTM

**Comment by nagem** [comment]
Incorporated into/replace by #1048
