### ISSUE TITLE
Reduce HTTP awareness in non handler layers

### ISSUE THREAD

**Issue by rentzso** [scitran/core#66]
As a general rule, classes should fall into two distinct categories:
- Classes that have functions named after HTTP verbs, and (basically) nothing else
- Classes that don't know anything about HTTP verbs or protocol details

Rather than self.abort, raise a variety of typed exceptions. This would be a better, drop-in replacement for what self.abort does anyway. At the very top, and/or whichever layers are appropriate, catch typed exceptions and handle a JSON error return there.

**Comment by gsfr** [comment]
Sounds like a good plan to me.

**Comment by gsfr** [comment]
Optional for bali-2, since no external impact.

**Comment by kofalt** [comment]
Renzo and I discussed the stack-trace logging in `base.py` today - one conclusion is that we can log stack traces in fewer scenarios when this is done.

Right now, a perfectly-reasonable non-200 is a stack trace in the log, and we can't easily get rid of it because there are instances of `self.abort(5` in the code ATM. After this ticket is fixed we can be more taciturn :)

**Comment by gsfr** [comment]
- [ ] create explicit request context map, stored on `self`
- [ ] never pass `self` (`RequestHandler`)
- [ ] never pass entire context map
- [ ] replace all `self.abort()` calls with `raise`
  - [ ] define `SciTranException` and inherit from it
  - [ ] create meaningful exception hierarchy using multiple inheritance using `SciTranException` and `webapp2.HTTPException`
  - [ ] catch all exceptions at the dispatcher level

**Comment by nagem** [comment]
As reworking of our error handling is done, we should keep this request from #243 in mind: 

>Here's one: better error messages. While building a feature I ended up trying to add a user to a group that was already in the group. The response was:
>
>HTTPNotFound: Element not added in list roles of container groups foo
>
>404 seems like the wrong error code for that, and it would've been more helpful if it told me why the request was rejected not merely that it was (ie. "User is already in that group").
