### ISSUE TITLE
Rename `group.roles` --> `group.permissions`

### ISSUE THREAD

**Issue by kofalt** [scitran/core#662]
1. Inconsistency (this is aliased away in the SDK)
1. Despite the name, roles are actually permissions in that they control R/W access to that group

**Comment by nagem** [comment]
Some general history/context around the separate naming:

Groups "roles" were considered permissions templates for when a user of a group creates a new project in that group. A user having rw or ro permissions on a group doesn't really give the user any new abilities involving that group, so groups were givens "roles" to imply the user's role didn't always grant them much for permissions. 

Over the course of time, this minor difference in key names has caused a lot of headaches for development. You will see many instances of:
```
perms = container.get('permissions', [])
if not perms:
    perms = container.get('roles', [])
....
```

Renaming the group key `roles` -> `permissions` will allow us to get rid of a lot of this logic. 

To Do:
  - Have a db upgrade script that renames the key on the groups collection
  - Scour the codebase looking for "roles", removing references to `roles` and using only the `permissions` key instead
  - Update any tests affected by these changes
