### ISSUE TITLE
Doc driven tests (abao) have maintenance issues

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#664]
Pain points to investigate
- [ ] Output schema file organization not intuitive
  - @nagem Provide context on pain with output schemas
- [ ] Order of execution is arbitrary 
  - confirmed due to js async loading
  - in practice, order has followed order in api.raml and sub raml files. Might be output printing only?
- [ ] Test inputs are managed in file location separate from the RAML documentation
  - confirmed that example in raml used
  - @ambrussimon-invenshure confirm if raml allows 1 example per result code
- [x] Dependency on prior execution of python or newman integration tests
  - Use common fixure loader for each test, rather than dependencies between test suites
  - Re-organize test scripts to support independent execution
  -  Postman tests alone satisfy abao
  - Test gear created with both postman tests and python integration

**Comment by ryansanford** [comment]
Spinoff of #600

**Comment by ryansanford** [comment]
@ambrussimon-invenshure suggests re-implementation of abao functionality we are currently using to python about 1 week full time effort. 

This could make it easier to add features not available in abao, but would not address things that are limitations of RAML (1 request body per method per route).

**Comment by kofalt** [comment]
That sounds great to me!
