### ISSUE TITLE
Groups do not update their modified field

### ISSUE THREAD

**Issue by kofalt** [scitran/core#665]
`group.modified` appears to always equal `group.created` :/

**Comment by nagem** [comment]
The `put` and `post` methods in `grouphandler.py` will need to be updated to set the `modified` key.

**Comment by hkethi002** [comment]
Should the modified field be updated whenever a role or tag is added, or just when the name is changed?

**Comment by kofalt** [comment]
Whenever any modification is made, so any of those scenarios would qualify.

The modified field should always represent the latest change to a document.
