### ISSUE TITLE
API keys are checked late in an upload

### ISSUE THREAD

**Issue by kofalt** [scitran/core#666]
When hitting a Targeted Upload, API keys are checked at the end of an upload, not the beginning. This makes it possible to sit there for an arbitrary length of time, only to fail at the very end :pensive: 

It might well be that this applies to other placers, and we should check.

**Comment by ambrussimon-invenshure** [comment]
@kofalt could you please help with reproducing? I've tried the following in an integration test pdb session:

```
(Pdb++) acq = data_builder.create_acquisition()
(Pdb++) t=time(); as_admin.post('/acquisitions/'+acq+'/files', files=file_form(('test.csv',500000*'TEST\n'))); print(time()-t)
<Response [200]>
1.86114692688
(Pdb++) t=time(); as_user.post('/acquisitions/'+acq+'/files', files=file_form(('test.csv',500000*'TEST\n'))); print(time()-t)
<Response [403]>
0.0149350166321
(Pdb++) 
```
The API returned with 403 right away when the unauthorized user tried to do the same upload, which is in line with what I've found in the upload logic.

**Comment by kofalt** [comment]
Hmm, I'll have a look tomorrow. It might be that things have changed in the meantime, or I was mistaken.

**Comment by kofalt** [comment]
So, I'm able to produce the problem with the python SDK with large files; try ubuntu ISOs.

It looks like the API does not throw a `APIAuthProviderException` until the entire upload form has been processed. In particular, if I add `print('Bad key')` right before `raise APIAuthProviderException` in `APIKeyAuthProvider.validate_user_api_key`, I don't see that statement print until the form is sent.

My guess is that we're accessing some property of the request / handler object in our init / auth code that coincidentally causes the consumption of the request body, not the request headers.
