### ISSUE TITLE
Support WeChat Login

### ISSUE THREAD

**Issue by dpuccetti** [scitran/core#675]
To support logging in with WeChat, we will need the following:

 1) A new item in the config that holds our WeChat App ID.
 2) Support for setting/storing usernames that are not email addresses.  The username for our example account is not an email address.
3) Changes to the login endpoint to enable WeChat auth.

The UI will use the App ID key to generate a WeChat login prompt.  When the user accepts, the UI will be given a code (think temporary token) for the user.  This code will be passed to the Core API.  The Core API will hit the following endpoint with the App ID, our App Secret and the code passed from the UI: `https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code`

The response from this request will be of the form:
```
{   "access_token":"ACCESS_TOKEN",
    "expires_in":7200,
    "refresh_token":"REFRESH_TOKEN",
    "openid":"OPENID",
    "scope":"SCOPE",
    "unionid": "o6_bmasdasdsad6_2sgVt7hMZOPfL" }
```

The openid will need to match the user's _id in the API.  The access_token could be passed to the UI to be used as an auth token.

The full flow: app->WeChat->app->API->WeChat->API->app

Documentation on the auth implementation can be found here: http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/web/login/login

**Comment by nagem** [comment]
This was fixed in #697
