### ISSUE TITLE
Provide description field for Projects and collections

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#676]
**Purpose**
Place for 1-2 paragraph description of the Project/Collection.

**Requirements**
- Length unbounded
- Only allow modification by Read/Write of respective Project or Collection
- Optional for Project/Collection creation

**Comment by nagem** [comment]
> Only allow modification by Admin of respective Project or Collection

We allow every other field to be edited by a `rw` user (including label). It would see unnatural to have a higher perm requirement for this field.

**Comment by ryansanford** [comment]
@nagem Please abide by the existing convention for this issue. I wanted to be explicit about permissions, and assumed a different convention when opening this issue.

Updating the description now...
