### ISSUE TITLE
Database responses require client-side validation

### ISSUE THREAD

**Issue by kofalt** [scitran/core#680]
Several endpoints will, when modifying or deleting a single object, will return with some variant of:

```json
{
    "modified": 1
}
````

This basically punts responsibility to the client to check this integer. Instead, the server should check that the count is one, and return an error and HTTP status code if mismatched.

On success, these endpoints could respond with nothing, or an empty json body.
`{ "success": true }` would not work because it recreates the same problem.

Known endpoints: ( PUT | DELETE ) ( group | project | session | acquisition | user )

**Comment by nagem** [comment]
To be clear, the API does check to make sure the deleted/modified/created number is 1 and throws a 400 if it is not.
