### ISSUE TITLE
Allow for grouping (folders?) of gear output

### ISSUE THREAD

**Issue by kofalt** [scitran/core#687]
> From @ryansanford
> Communication regarding this enhancement should be directed through https://flywheelio.ideas.aha.io/ideas/FW-I-75.

This could / should probably be tracked with the [gear spec](https://github.com/flywheel-io/gears/tree/master/spec), but I'm going to leave it here since the concept has to map well to the scitran hierarchy and flywheel user interface.

@cgc has a gear that produces output like so:

```
output/
├── mean_image
│   └── meanusub001-t1_reoriented.nii
├── realigned_unwarped_files
│   └── usub001-t1_reoriented.nii
├── realignment_parameters
│   └── rp_sub001-t1_reoriented.txt
├── stderr.log
└── stdout.log
```

His request, from #591:

> how feasible is adding support for nested files? I don't need support in the interface for them yet, I only need their names to be preserved, so something like "files": [{"name": "mean_image/meanusub001-t1_reoriented.nii", ...}, ...] for the above would be ideal, so my scripts can filter by things that have mean_image/ as a prefix.

My thoughts on the idea:

> I think the main challenge with folders in containers would be that it breaks some assumptions:
> 
> 1. Do we let folders map to hierarchy?
> 1. If so, what implications does that have on gears running at level X? Is it "okay" for a gear running at the session level to create or write to existing acquisitions? What's the plan if folders are created in a place that can't be mapped to hierarchy (acquisitions)?
> 1. If not, what do we do when we export to BIDS format? Is that folder prefix lost?
> 
> It does seem reasonable that a gear should be able to semantically group output into categories. Right now it's only one clump instead of several. I'm going to break out that idea into a separate ticket and ping some people :slightly_smiling_face: 

There's probably more to it than that, but let's see what ya'll think. Assigning to the main crew.

**Comment by kofalt** [comment]
Oh, and to clarify, the current behavior is that folders in the output are totally fine, but should be ignored. The files will be saved to the hierarchy flat, as if there were no folders.

There might be a bug with that current behavior, which is tracked by #591.

**Comment by gsfr** [comment]
FWIW, @rentzso and I recently added support for nested files to the openneuro fork. We basically allowed filenames contain `/` characters and adapted the download functions to respect those. No complaints so far.

**Comment by kofalt** [comment]
That sounds like my number-three bullet, right?
Saving folder path in the file name, but in most other respects ignoring them?

**Comment by cgc** [comment]
**re: 1 and 2** I didn't know gears could modify acquisitions or sessions, and I don't intend to use them that way; I only intend to produce new analysis. I can see a number of possible schemes that can work for this. The examples below are attempting to describe a file `file.nii.gz` that is in a directory `directory`.

This scheme is what I assumed flywheel would do and seems like a pretty plain scheme (and seems like the scheme @gsfr and @rentzso have adopted):
`"analyses": [{"files": [{"name": "directory/file.nii.gz", ...}, ...], ...}, ...]`

This scheme may result in `name` not being unique if files can have same names (for the reason I describe below, i'm concerned about this for my data processing), but is otherwise not too bad.
`"analyses": [{"files": [{"name": "file.nii.gz", fullPath: "directory/file.nii.gz", ...}, ...], ...}, ...]`

I can imagine file alternatively having a `dirname`, or files containing `files` arrays, but those schemes seem clumsier in practice.

**re: 3** [BIDS format](http://bids.neuroimaging.io/bids_spec1.0.1-rc1.pdf) does not seem to recommend a particular structure for "data derivatives".
> BIDS in its current form is designed to harmonize and describe raw (unprocessed or minimally process due to file format conversion) data. During analysis such data will be transformed and partial as well as final results will be saved. Derivatives of the raw data (other than products of DICOM to NIftI conversion) should be kept separate from the raw data.


section 3.4 does have this recommendation
> We do recommend keeping them in separate “sourcedata” and “derivatives” folders each with a
similar folder structure as presented below for the BIDS-managed data.


but isn't otherwise prescriptive.


In general, flattening any hierarchical structure can result in pieces of data with the same name (at the very least, running `basename(filename)` can almost certainly result in files with the same name if different folders contain the results of processing that are very similar (with small changes to parameters), which my pipeline does). The potential for data loss and lack of a simple general solution makes me want to strongly urge avoiding flattening the hierarchy in the post-engine phase and instead force the decision about hierarchy flattening to occur inside of any BIDS conversion tools.

**Comment by lmperry** [comment]
Here's the implementation that @gsfr and Renzo contributed to OpenNeuro. 

https://github.com/poldracklab/bids-core/pull/12/files

Can we get some consensus on this implementation and start forging a path forward? Right now we're having to flatten (or zip) output folder structures and it would be great to not require that of gear authors.

**Comment by cgc** [comment]
@kofalt wanted to check in and see if there's any ETA for a fix to this issue

**Comment by kofalt** [comment]
Thanks for the ping - I'm afraid a few other things held my attention for awhile.

Also thank you for your callout of relevant snippets of the BIDS spec. I've not yet had much contact with it, but I'll definitely be giving the spec a read tomorrow. My earlier statement about exporting to "BIDS format" wasn't very clear or accurate: when we offer bulk downloads (in the UI, select a few sessions on the left and hit Download under Actions), we send over a tarball with this layout:

```
/<group>/<project>/<patient_code>/<session>/<acquisition>/
```

With relevant files attached in the project, session, and acquisition folders. Your comment about "the decision about hierarchy flattening to occur inside of any BIDS conversion tools" sounds like a good idea, and so we'd have to accomplish that here, and maybe some other places.

The PR linked by Michael looks reasonable, but at first glance I'm not confident it handles filename collision during export, which we should probably solve. OS-style "(1)" renaming? Rejection?

Fundamentally, I would prefer if gear outputs were always their own set of files, rather than intermixed into others - it would make this sort of thing a lot more obvious. For analysis-style gears this is easier to handle, and display in the user interface.

For this to get rolling, I think we need Ryan / Michael / Gunnar to put their heads together and figure out how this feature should work - including user interface concerns - and Megan or I could implement it, probably using poldracklab/bids-core#12 as a starting point.

**Comment by ryansanford** [comment]
@cgc 
Regarding your statement "so my scripts can filter by things that have mean_image/ as a prefix"  
- How does your script interact with the core API, or does it interact with the local filesystem after download of an analysis?
- Are there algorithms you expect to use, or are commonly used by others that produce nested output?
  - If so, what are they?
- What assumptions should gear authors have around consuming these nested outputs as inputs into a different gear?
- Add anything else that could help us understand the value of this request as scoped, and a more  complete story that could include UI and search extensions.

Thanks!

**Comment by kofalt** [comment]
That's an interesting point - if a file that happens to have a folder should be placed in that folder when provided to a gear as an input. My intuition would be a strong **no**, since gears only acknowledge single files as inputs right now & there's no reason to make them chase a folder structure looking for it.

But we've had container inputs on our mind for a long time (probably `"base": "folder"` rather than `"base": "file"`) and in that scenario it might make sense to provide any saved folder structure.

**Comment by cgc** [comment]
background: I have a set of scripts that run pipelines in flywheel: by specifying a sequence of operations using gears, and specifying which files in acquisitions and analyses are the inputs to the gears, my scripts can manage running these sequential pipelines for N sessions at a time. Here's an [example script](https://github.com/scitran/python-client/blob/3b40324e70ebfd3eb1c38ffe34951473cdfb576c/examples/flywheel_analyzer_afq.py): it runs the dti init gear and connects that output to the afq gear. This code doesn't download any files: it loads the lists of acquisitions and analyses from the server and does filtering in python to find the appropriate files to specify as inputs to gear execution. Implementation details for underlying library are [here](https://github.com/scitran/python-client/blob/3b40324e70ebfd3eb1c38ffe34951473cdfb576c/scitran_client/flywheel_analyzer.py).

I also have a script that downloads relevant files from flywheel: nifti images, analyses outputs, uploaded behavioral/stimulus files.

with that out of the way, I'll answer your questions

- my analysis script filters server listings of analyses output using `fnmatch()`, so I can specify things like `find(acquisition, label='functional').find_file('*.nii.gz')` or `find(analyses, label='preprocessing').find_file('mean_image/*')` and get a valid input to kick off a gear. my download script downloads files to the server where we do group analysis; I'll likely toss an `os.makedirs(os.dirname(file['name']))` into that script.
- I use nipype, which outputs files in folders by default (the format I've shown examples from in other issues). Michael tells me that freesurfer has a very deeply nested directory structure. Additionally, some of the vista soft tools (DTI init in particular) seem to output nested directory structures (today we just zip the DTI init output).
- I assume that all inputs to a gear are in standard nipype format (directory named after input key in manifest, file with its name). However, some of the cases above (the DTI init output, which must just directly be passed to AFQ, in it's current structure) are a bit harder to figure out the product implications for (do you mark the DTI init folder (with all of its nested folders and files) with some kind of metadata that makes it in effect a typed object and pass in that typed object to AFQ? or do you enumerate every file from the DTI init in the AFQ manifest and pass each file in individually, although perhaps with some way of specifying nesting, like an input key with forward slashes?)
- i'm treating this last bullet as a bit of a soap box
    - Search isn't useful for me: my project has 100s of sessions and in total, 1000s of files, but I rely on simply downloading the list of sessions, and for each session, filtering through files. when filtering on 1000s of objects, I find simple logical operators to be clearer and simpler (and more likely to be correct) than dealing with a search engine.
    - When I'm first testing out my gears in the UI, it's incredibly complicated to correctly find the output of one gear that should be the input to the next: particularly with nifti files across all the tasks one subject does, I have to carefully read through a list of 100s of nifti files. I'm not sure how this can be solved: metadata on inputs to gears that specify some subtype of nifti file (aligned to MNI152, or slice-time corrected), or that specify some source (smoothed output from the `reactivity-preprocessing` gear. I could also see an extension to session templates that says outputs from one gear execution should be input to another.).

**Comment by ryansanford** [comment]
@cgc 
Thanks for the quick response.

We will track this request at https://flywheelio.ideas.aha.io/ideas/FW-I-75. Feel free to add any more context there. We will update the status there as soon as it is available.
