### ISSUE TITLE
Expose Connector ID in API

### ISSUE THREAD

**Issue by dpuccetti** [scitran/core#692]
Displaying the connector ID was requested as part of an unrelated issue for the frontend.

**Comment by kofalt** [comment]
@lmperry Can you elaborate what this means?

**Comment by lmperry** [comment]
![screen shot 2017-03-14 at 2 02 48 pm](https://cloud.githubusercontent.com/assets/2119651/23922295/0a9f7b3e-08bf-11e7-9f3a-a85ada78d23e.png)

I don't think this requires any core work as the only required information is the group ID and the project name. 

Like so:

![screen shot 2017-03-14 at 2 05 31 pm](https://cloud.githubusercontent.com/assets/2119651/23922411/7bb55082-08bf-11e7-95f4-80da5a679c95.png)

**Comment by dpuccetti** [comment]
@lmperry I was unable to find the connector ID in the api.

**Comment by kofalt** [comment]
It seems reasonable that the API should provide this - I wouldn't want that text transform implemented twice. Based on Megan's comments, it is: group ID, slash, (project name --> lower case --> spaces to underscores).

We could return it on the /projects and /projects/<id> endpoints. Field name of `code`?
