### ISSUE TITLE
Abao delete gear test failing after related change/fix

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#696]
https://travis-ci.org/scitran/core/builds/211166055

@ambrussimon-invenshure This test may get skipped to resolve the CI failure. Final resolution would be to get gear deletion working at a minimum in abao or python integration tests.

**Comment by kofalt** [comment]
```
InvalidId: 'undefined' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
```

Looks like this test never worked, and making the endpoint function exposed that. I'll push a skip.

**Comment by ambrussimon-invenshure** [comment]
This is odd, I remember running into and fixing this once - maybe I somehow skipped that commit, but then I don't get how CI seemed green on the freshly rebased branch before the merge to master. Anyhow, sorry and thanks!

**Comment by ambrussimon-invenshure** [comment]
Ah, that was because I ran into this when fixing gear deletion on the increase-coverage-of-api-jobs-handlers branch which isn't merged yet. @ryansanford gear deletion coverage was added to py int tests there, too.
