### ISSUE TITLE
Set of batch states != set of job states

### ISSUE THREAD

**Issue by kofalt** [scitran/core#710]
Two different enums :pensive: 

Renaming batch `launched` to `running` would solve it.

Arguably, batches could also get `complete` and `failed`, but... eh.

**Comment by nagem** [comment]
Launched cannot be renamed to running because they mean different things. We "launch" batch processes and that is their final state, unless they are cancelled. Right now there is no way of knowing without a cron when all jobs in a batch process reach a final state (like "complete" or "failed").

**Comment by kofalt** [comment]
How would you feel about modifying the job-complete behavior to check if it's part of a batch, and set the batch status to `complete` if all jobs are complete? Then batches would have the same basic flow.

**Comment by nagem** [comment]
That's a good idea, we can do that 👍

**Comment by hkethi002** [comment]
Any thoughts on when the batch should be set to failed? I was thinking when all the jobs are either complete or failed, with at least one job's state as failed.

**Comment by kofalt** [comment]
I would say that batches should probably never be marked as failed, unless (maybe) every single job failed. Batches are intended to launch large amounts of work, on sets of data that may now always match perfectly what a gear wants to consume.
