### ISSUE TITLE
batch/<x>/jobs endpoint does not exist

### ISSUE THREAD

**Issue by kofalt** [scitran/core#711]
`BatchHandler.get_jobs` --> does not exist, despite what the [router says](https://github.com/scitran/core/blob/50328b996827347a18b5e725061dd9ba22fe2a6a/api/api.py#L158).

Looks like this turned into a flag on `BatchHandler.get`.

**Comment by ambrussimon-invenshure** [comment]
Referenced the PR # in the [PR](https://github.com/scitran/core/pull/809) by mistake, closing manually. Thanks for merging @kofalt!
