### ISSUE TITLE
Invalid API key results in a 500

### ISSUE THREAD

**Issue by kofalt** [scitran/core#739]
```js 
// $ http api/users/self 'Authorization:scitran-user bad-key'
{
    "message": "Unexpected error.", 
    "status_code": 500
}
```

Ref #66, #471.

**Comment by kofalt** [comment]
Adding SDK label since this results in confusing errors to the user.

**Comment by ryansanford** [comment]
@nagem I assigned this to Ambrus to work on while he's blocked on reaper.

**Comment by nagem** [comment]
@ryansanford Sounds good 👍.

@ambrussimon-invenshure  There are comments about this problem in the code, as well as on this PR: https://github.com/scitran/core/pull/733. Here is what I remember from trying to fix it quickly the first time:

It's really just a hierarchy/inheritance problem. I'd like to keep using named exceptions in the auth logic, so a solution would involve preserving those and not just switching them to call `self.abort()`. I think I attempted to raise the caught exception by calling `self.handle_exception()` directly in the init, but ran into a more complicated issue - if you can get that to work that might be a nice solution.
