### ISSUE TITLE
Add ability to see group display information when user does not have access

### ISSUE THREAD

**Issue by nagem** [scitran/core#762]
In the situation where a user has permissions to a project but not to the group the project is in, it is hard to display information about the project's group because the user's client cannot load this information. 

Proposals:

1. Open group endpoint to users that do not have >= `ro` permissoins, perhaps only with display related info
2. Add group display information to project GET endpoints (either always or through a query string flag)

**Comment by nagem** [comment]
This endpoint does exist, but it doesn't give the user's permission information. This ticket now requests making improvements to `/api/projects/groups`

**Comment by lmperry** [comment]
cc @dpuccetti

**Comment by dpuccetti** [comment]
@lmperry It will reduce the number of API calls required on the projects page.  For example, the projects page currently requires separate api requests to get the groups for the project list and the groups for the new project modal.
