### ISSUE TITLE
Subject age sometimes a float

### ISSUE THREAD

**Issue by kofalt** [scitran/core#773]
On our dev site:

```
>>> sessions = fw.GetAllSessions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "flywheel.py", line 49, in GetAllSessions
    return self._handle_return(status, payload)
  File "flywheel.py", line 38, in _handle_return
    raise FlywheelException(result)
flywheel.FlywheelException: json: cannot unmarshal number 1009152000.0 into Go struct field Subject.age of type int
```

From our [data model](https://github.com/scitran/core/wiki/Data-Model):

> age 	int 	age at time of session in seconds

**Comment by nagem** [comment]
I just looked at our json schema and it's using `number` not `integer`. Changing that should fix the problem.

We'd need a simple db update to `int()` all the floats it finds but shouldn't be hard.

**Comment by gsfr** [comment]
Please get this fix in asap. It's blocking use of the SDK.
