### ISSUE TITLE
Do not allow non-https avatar URLs

### ISSUE THREAD

**Issue by nagem** [scitran/core#776]
Creates "mix-content" warning on browsers. Also rectify any existing http avatar URLs.

**Comment by kofalt** [comment]
> rectify

Remove?

**Comment by nagem** [comment]
I proposed we could attempt to change to https and see if it resolves, resaving if so, deleting if not. But it's probably best to just wipe them.

**Comment by kofalt** [comment]
_(Just writing down offline discussion here)_ I would support removal over trying to correct. How many users could possibly have saved an HTTP avatar that serves but does not redirect to HTTPS...

![](http://i0.kym-cdn.com/photos/images/original/000/782/935/ce2.png)
