### ISSUE TITLE
DB update #26 adds gear name to tag list regardless of tag already being present

### ISSUE THREAD

**Issue by nagem** [scitran/core#785]
Some jobs were already tagged with their gear's name in existing data sets so `upgrade_to_26` ends with some jobs having the gear name listed twice in the job tag list.

Since double tags don't really cause any issue, we're just going to update the existing db update instead of creating a new one that cleans up the problem. 

If there is an efficient way to only process jobs that don't already have the gear tag that would improve the speed at which this update runs as well. Maybe get a list of all gear names from the gears table and then modify the `find` on the jobs table to only return jobs that don't have any tags that match the list of gear names.

**Comment by nagem** [comment]
@kofalt FYI

**Comment by kofalt** [comment]
¯\\_(ツ)_/¯
