### ISSUE TITLE
Engine upload should a̶c̶c̶e̶p̶t̶ handle invalid metadata

### ISSUE THREAD

**Issue by kofalt** [scitran/core#795]
Currently, a gear's output - files and metadata - are dropped if there is a metadata validation error. This isn't visible to the end user, and risks losing a lot of work.

My proposal would be that:

* The metadata (invalid or otherwise) is saved on the job object, as it normally would be.
* The metadata is **not** applied to the destination container. Duh.
* The files are accepted. It's too confusing for a non-author to do otherwise: "where's my files?!"
* The job gains a new field, saving the validation error for later use.
    * Show that error, along with original metadata, in the UI when viewing job logs.
* Consider having the UI highlight the files when their origin is a job that has this issue.
* ~Maybe the job gains a new state as well, `invalid`? Not sure I like that.~
* Ideally, files produced in this error condition would not trigger other jobs.

Example follows, ref scitran-apps/dicom-mr-classifier#4:

```
16:27:29 base.py:427 from None None POST /api/engine {u'job': u'5923108aa56881001eb8409b', u'id': u'5923108aa56881001eb84099', u'level': u'acquisition'} request_id=bbc36a4a-1495470449
16:27:29 base.py:332 788400000.0 is not of type u'integer', u'null'

Failed validating u'type' in schema[u'properties'][u'session'][u'properties'][u'subject'][u'allOf'][0][u'properties'][u'age']:
    {u'type': [u'integer', u'null']}

On instance[u'session'][u'subject'][u'age']:
    788400000.0 request_id=bbc36a4a-1495470449
16:27:29 POST /api/engine?id=5923108aa56881001eb84099&job=5923108aa56881001eb8409b&level=acquisition => generated 314 bytes in 9 msecs (400)
```

**Comment by kofalt** [comment]
I'm going to let this sit for perhaps a week, then assume we're in agreement.

**Comment by lmperry** [comment]
I have gone back and forth on this over the course of the day... whether bad metadata should render the run a failure and thus discard the outputs altogether. The bottom line for me is that the gear was meant to do something and, and in this case it didn't do it. I agree that it's confusing to not have files show up because the metadata were invalid, however, if those things go together, or the metadata is required as part of an analysis pipeline (that's getting ahead I know) then I would want to know that happened and I would consider that a gear execution a failure. What makes me uneasy is that this is a second-order failure, in that the gear actually executed without failure (exit code = 0), but the api will reject the result. We would have to make that very clear in the UI, be it by displaying another state or something else.  

Other thoughts?

**Comment by kofalt** [comment]
I agree with you in principle. But, I think two things are very clear to me:

1. We IMO don't have any option other than showing the result files where they would display normally. There is just no way Joe Non Author can be expected to understand his gear didn't work, and instead the results are hiding three tabs to the left and a modal down, or something.

1. Gear metadata failure has the potential to be --> therefore will be unpredictable. Edge cases that aren't frequently / ever activated, buggy code, divergence. I saw the classifier change ("our" fault, we got more strict about a key) because I was watching the engine logs, but in a bug bash we probably wouldn't have seen it unless checking the long provenance tab.

For these reasons I'm preeeetty convinced we should put the files where they'd normally go, and use the origin field to highlight them in the UI. Maybe these files can be red, and clicking them brings up a modal explaining the job failure, or something. Visible in the same place you'd go for successful results.

I agree that data could be invalid if the metadata is missing - what if we offered an option to delete all produced data when they're viewing the "why this job failed" UI?

I also like your comment about pipelines. Files produced by a "semi"-failed job should probably not trigger other jobs! That could definitely be part of this change.

Finally, long ago I offered the idea that gears could choose this behavior. Basically:

```js
{
   // ...
   "on-metadata-failure": "continue || reject || warn"
}
```

In this case the default would be `continue` (the proposed behavior above), but you could be more strict as desired.

**Comment by gsfr** [comment]
I continue to agree with @kofalt. Outright rejection is not a option, and neither is calling the job run a success. Prominent indication of "metadata failure" seems prudent.

**Comment by kofalt** [comment]
Sounds good. Proposal accepted; the gear-spec field can be a future enhancement.

**Comment by ryansanford** [comment]
Proposal looks reasonable to me given the current state of affairs. I presume that this will be re-visited when pipeline support becomes more refined.

Will the same proposal be applied for non-validation related metadata errors, such as Json can't be parsed, metadata too large for mongo storage, other?

Related to offering flexibility with this behavior in the future. If that becomes a reality, users should have the ultimate authority, not the gear authors.

Regarding pure classifier gears, where output is metadata for the input file, and not any output files: I presume that the job would still go into a failed status?

**Comment by kofalt** [comment]
> I presume that this will be re-visited when pipeline support becomes more refined.

I hope not: the job still goes into a failed state, this is just a more specific interpretation of the failure. But maybe there's more nuances there, if a pipeline discussion ticket is filed I'll definitely read with interest.

> Will the same proposal be applied for non-validation related metadata errors, such as Json can't be parsed, metadata too large for mongo storage, other?

No, because I don't think it's realistic to handle those cases. This is very specifically for metadata that we don't accept; the gear is still responsible for acting reasonably.

> users should have the ultimate authority, not the gear authors.

Mmm, I don't agree, but we can worry about it another time :)

> Regarding pure classifier gears, where output is metadata for the input file, and not any output files: I presume that the job would still go into a failed status?

Correct. This only changes the job object, not the file objects (or lack thereof).

**Comment by ryansanford** [comment]
> > Will the same proposal be applied for non-validation related metadata errors, such as Json can't be parsed, metadata too large for mongo storage, other?
> 
> No, because I don't think it's realistic to handle other cases. This is very specifically for metadata that we don't accept; the gear is still responsible for acting reasonably.

@kofalt I don't think your response is wrong. It does move the needle further away from simple and predicable API behavior. Is it not realistic due to implementation complexity, or would it lead to negative user satisfaction?

**Comment by kofalt** [comment]
Implementation complexity. In general anything touching I/O is pretty complex, with a lot of edge cases and legacy platform issues

**Comment by kofalt** [comment]
Some variant of this landed in https://github.com/scitran/core/pull/1015. I cannot promise the exact proposal was implemented; your best bet would be to give the source a look.
