### ISSUE TITLE
Error return improvements

### ISSUE THREAD

**Issue by kofalt** [scitran/core#807]
Relates #690, #525, possibly others. Raised via support conversation with @cgc. 

1. Every error response needs to be constrained to the same struct, with optional fields. For example, as per #690 the validation error could be a field that is left blank for non-validation errors.

1. Contain the request ID as per #525.

1. Megan & I have been talking about error codes for awhile - in addition to / supplanting the HTTP status code, we need permanent integers that describe the problem. My guess is these could be associated with various Exception types under the hood, and be shipped next to human-meaningful messages for the _category_, as well as the current instance-specific message.

1. More?

**Comment by hkethi002** [comment]
With the improvements to our Exceptions, such as the addition of our own internal codes, any thoughts on moving away from the self.abort and calling the webapp2 Exceptions to our own?

**Comment by kofalt** [comment]
I don't have an opinion at the moment, but in general the less ties to webapp2 we have, the better. It's hopefully not long for this world.
