### ISSUE TITLE
Analyses should be their own doc in mongodb

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#808]
Stepping stone to ease analyses interaction with jobs and search.
@nagem add other benefits here as well.

Phase 1:
- [ ] No functional changes to API
  - jobs & batch changes would be significant.
- [x] Migrate existing analyses out containers into their own collection using `bin/database.py`.
  - sessions
  - collections
  - @nagem Any other containers supported that need to be accounted for?
- [x] Add appropriate index for efficient lookup/join
- [ ] Add tests for missing coverage
- [ ] Update search replication code in dependent 

Followup work would be proper support in jobs, batch and resolver for analyses within any supporting container.

**Comment by nagem** [comment]
Sessions and collections, in practice, should be the only containers with analyses but they are technically supported at the project and acquisition level as well. I would just ensure the db update checks all containers based off the Container type on the data model wiki page.
