### ISSUE TITLE
Simplify FileListHandler 

### ISSUE THREAD

**Issue by rentzso** [scitran/core#81]
This `get` method in FileListHandler has high cyclomatic complexity.
https://github.com/scitran/api/blob/master/api/handlers/listhandler.py#L290

A simple refactoring should improve readability and maintainability.
Final goal should be to write consistent unit tests.

Also, propagate functions under Permission and Tag ListHandlers should be moved to keep all DB access confined in dao files.

**Comment by nagem** [comment]
Fixed in #298
