### ISSUE TITLE
Update api-console for anchor support

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#828]
Upcoming version 4 of API console will support anchoring. This makes it easier to point collaborators at relevant API documentation.
https://github.com/mulesoft/api-console/issues/60

Github served docs for this repo are at https://github.com/scitran/core/blob/master/docs/api/v1/index.html

and hosted via: https://scitran.github.io/core/api/v1/index.html?branch=master

**Comment by ambrussimon-invenshure** [comment]
@ryansanford looking into this I found that we basically have api-console's [/dist](https://github.com/mulesoft/api-console/tree/master/dist) copied to [docs/api/api-console](https://github.com/scitran/core/tree/master/docs/api/api-console) and patched to point to api.raml on master. Ran the console w/ sources updated to v4, but I think that the deep linking/*anchoring feature is not part of that interface*.

Building the docs with their recommended [cli tool](https://github.com/mulesoft/api-console/blob/master/docs/build-tools.md#cli) gave a different console that *supports anchoring*: [(demo)](https://mulesoft.github.io/api-console/#/docs/summary).

If the interface difference is not a problem, then I suggest switching to the latter approach. (This will however need an additional CI step for building the console!)

**Comment by ryansanford** [comment]
@ambrussimon-invenshure Is there a way to use the cli tool to generate a console  that can be pointed at arbitrary raml url like described here? https://github.com/mulesoft/api-console#raml-data-source

Makes me think we could essentially use the cli tool to generate what used to be provided via the `/dist` folder from the api-console.

**Comment by ambrussimon-invenshure** [comment]
@ryansanford That paragraph indeed describes the possibility of on-the-fly-raml-load which I missed before, thanks! It uses the [embedded element method](https://github.com/mulesoft/api-console#embed-as-an-html-element) and is a different solution to both the /dist and the cli build method.

I'm looking into the viability of this right now. Right off the bat my first question is whether storing ~75M of bower_components is OK within the repo, as that seems to be a requirement... (To be fair the old api-console/dist folder that's already in core is 21M)

**Comment by ryansanford** [comment]
Wow, that's a lot of code to facilitate the api console. Does it not support the deep linking then?

What's the storage requirement for using the method that requires their cli tool and CI to update the docs on github?
