### ISSUE TITLE
Add support for generic Object Storage for files

### ISSUE THREAD

**Issue by nagem** [scitran/core#837]
- [ ] Add an `ObjectStorage` class that will serve as an interface for `<>ObjectStorage` classes that can handle file I/O using different storage backends like POSIX, S3, Google Cloud, etc.
     - [ ] download
     - [ ] upload
  - [ ] Implement the `POSIXObjectStorage` (name can be debated) class to do support current functionality
  - [ ] Add config key to mark default storage option. Will default to `posix`
  - [ ] Add additional keys to file objects in the db to designate which type of storage the file is using
  - [ ] Modify file upload and download logic to determine file storage type (config for upload, file object for download) and instantiate proper `ObjectStorage` class to handle actions

**Comment by kofalt** [comment]
Wish list: I/O that can take and return file-like objects
