### ISSUE TITLE
Is it possible to remove config dupe key race?

### ISSUE THREAD

**Issue by kofalt** [scitran/core#844]
I'm seeing [transient CI failures](https://circleci.com/gh/flywheel-io/sdk/157) with error:

```
(500) E11000 duplicate key error collection: scitran.singletons index: _id_ dup key: { : "config" }
```

Here's [what I'm using](https://github.com/flywheel-io/sdk/blob/bd85a1b7ead2bca6be3523dfe54081fb8437b54b/.circleci/config.yml#L22-L28) to boot scitran, from an utterly clean slate:

```
cd /var/scitran

python /var/scitran/code/api/bin/database.py upgrade_schema

/var/scitran/uwsgi-entrypoint.sh uwsgi --ini /var/scitran/config/uwsgi-config.ini --socket "[::]:9000" --processes 4 --threads 2
```

Do you think there's a way to fix this transient failure?
Possible relation to #212?

**Comment by gsfr** [comment]
Looks like we should be doing certain init tasks before uWSGI forks. Colton seemed to think that was possible. That's all I know.

Apologies for the utterly useless comment.

**Comment by kofalt** [comment]
Cool, that's somewhere to look then!

**Comment by kofalt** [comment]
Just a note that I saw this [again](https://circleci.com/gh/flywheel-io/sdk/168) today, with a new key:

```
'(500) E11000 duplicate key error collection: scitran.groups index: _id_ dup key: { : "unknown" }'

...

'{"status_code": 500, "message": "E11000 duplicate key error collection: scitran.singletons index: _id_ dup key: { : \"config\" }"}'
```

I thought `_id_ dup key: { : "unknown" }` was a little interesting...

**Comment by kofalt** [comment]
This ain't fixed
