### ISSUE TITLE
Add one-job use token/api key generation for use within gear

### ISSUE THREAD

**Issue by nagem** [scitran/core#850]
If a job created by a user wishes to access core data during the execution of said job, we would need to auth to core using that user's creds. One option to support this would be to lookup the uid in the origin of the job, and generate a temporary auth token for that user when the job is started via `jobs/next`. The auth token would allow requests to auth as that user, and would only be accepted by the API while the job is in a `running` state. 

More discussion on this topic is expected, feel free to discuss specifics and other ideas below.

**Comment by nagem** [comment]
Another option is to allow an engine to "masquerade" as the user identified in the origin.

**Comment by kofalt** [comment]
Notes:

1. The token has to be a valid API key
1. I would _liiiike_ the keys to use the same subsystem as normal API keys
1. The token must only be accepted when the job is in state `running`
1. The token must not be saved to the database

**Comment by kofalt** [comment]
Closed in #938
