### ISSUE TITLE
Possibly update created date, replace all file fields on file replace

### ISSUE THREAD

**Issue by nagem** [scitran/core#878]
When a file with the same name as an existing file in a container is uploaded, it replaces the file itself and updates the file attributes stored in Mongo, preserving some of the old values like `created`.  It is possible we'd want to replace all fields and treat it as a new file. Further thought/discussion required.

**Comment by kofalt** [comment]
:+1: to this. Replacing a file blob should definitely not keep old attributes around.

We should strive to be immutable wherever possible; I treat it as an unfortunate concession that we allow for file replacement at all. Not to mention it's a serious race condition for gears :/

Pinging @gsfr for his thoughts.

**Comment by gsfr** [comment]
Agreed. If the new file is different, it should be treated like a new file, whereas "replacement" with an identical file should be treated as a no-op.

**Comment by kofalt** [comment]
Ah, so this?

```python
def replace(new, old):
  if new.hash == old.hash:
    # do literally nothing, including no modified update; return 304 Not Modified
  else:
    # delete all classification / info / whatever fields; store new; return 200
```

**Comment by gsfr** [comment]
@kofalt Yup.

@nagem That reminds me, do we still have that "identical zip file" check in our code? I recently verified that the reaper produces bit-identical zip files on repeated reaps.

**Comment by nagem** [comment]
@gsfr I haven't seen anything like that in our code before, and doing a quick check in the likely places didn't turn up anything.

**Comment by kofalt** [comment]
Yeah, I think that bit of code died a glorious death awhile back :wink:

**Comment by gsfr** [comment]
Glad to hear it
