### ISSUE TITLE
Better sanitization of file I/O

### ISSUE THREAD

**Issue by kofalt** [scitran/core#89]
#86 closed the loop on security vulns, but untrusted input could still perform a variety of annoying tasks:
- 300,000 character whitespace-not-whitespace unicode filenames
- Behaviour of system when code points are passed that aren't valid for the filesystem?
- Different filesystems have different opinions (OSX ain't case sensitive, etc), what's our minimal subset?
- Let's assume there's an escape for `os.path.basename` since I didn't validate

Closing this requires at minimum:
1. Thoughtful sanitization of untrusted input
2. Handling of post-sanitization collisions
3. Test cases that confirm failure to escape / cause trouble

**Comment by gsfr** [comment]
We no longer store filenames in the filesystem.

Remaining todos are
- restricting filename length
- verify that filename does not contain a `/`.

```
os.path.basename(filename) == filename
```

We couldn't find any known escapes to `os.path.basename`, but the following should take care of that eventuality as well. But we will live on the edge and not do that.
```
os.path.commonprefix([storeage_path, os.path.abspath(os.path.join(storeage_path, filename))]) == storeage_path
```

**Comment by kofalt** [comment]
:+1:

**Comment by kofalt** [comment]
Assigning to @nagem, mostly so she can decide if this should be closed or not. 

I'm wondering if our schemas do enough here, or if this should stay open?
