### ISSUE TITLE
Add parent container to search results

### ISSUE THREAD

**Issue by dpuccetti** [scitran/core#896]
The parent container was previously returned with search results, but this is no longer the case.

**Comment by nagem** [comment]
This commit organized the whitelist for return fields, but it seems some of the fields were lost in the transition: https://github.com/scitran/core/commit/3cffedad48d159663dcbb2af757ffa0284a02168

@hkethi002 mind adding the lost keys and making sure the list before and after is the same? I also see `analysis.parent` which doesn't exist, objects with parents reference them via `parent`.
