### ISSUE TITLE
Analysis Improvements

### ISSUE THREAD

**Issue by nagem** [scitran/core#908]
- [ ] Split analysis into `files` (outputs) and `inputs`. Inputs are a reference to files on another container and should be secondary to files only attached to the analysis 
 
 - [ ] Keep `job=true` logic for `POST api/<container_name>/<container_id>/analyses`, move default behavior to new endpoint, possibly `POST api/<container_name>/<container_id>/analyses/legacy`

 - [ ] Make job inflation optional when requesting an analysis/many analyses

 - [ ] Add routes to access analyses directly. Leave existing routes for now (?)
    - `analyses/<id>`
    - `analyses/<id>/files`
    - `analyses/<id>/files/<filename>`
    - `analyses/<id>/notes`
    - `analyses/<id>/notes/<id>`

Note: Keeping breaking changes minimal to the "old" analysis upload type is important while also phasing out/redesigning that use case.

**Comment by kofalt** [comment]
SDK-relevant: 
1. Analysis files aren't normal files; need to be split into two keys and remove the `input` & `output` keys
1. Jobs are always inflated / joined when fetching an analysis
1. `&job=true` flag indicates new behavior on `/analyses`; should be default

**Comment by nagem** [comment]
`GET api/analyses/<id>` was added as part of #938. It was changed to ignore parent information in the initial `get_container()`.
