### ISSUE TITLE
Jobs triggered from rules should use their default config

### ISSUE THREAD

**Issue by kofalt** [scitran/core#923]
Right now, jobs that are launched via a rule end up with an empty config. Before the job is stored in the database, we should ensure it has the proper config - in this case, copying over the default config.

Probably a dependency of #922.

Additional details added by @nagem:

Gear documents stored in mongo will have a `config` field (possibly empty). An example:
```
"config" : {
            "multiple" : {
                "exclusiveMaximum" : true,
                "description" : "Any two-digit multiple of ten.",
                "default" : 20,
                "multipleOf" : 10,
                "maximum" : 100,
                "type" : "number"
            },
            "string" : {
                "default" : "Example",
                "type" : "string",
                "description" : "Any string."
            },
            "number" : {
                "default" : 3.5,
                "type" : "number",
                "description" : "Any number."
            },
            "phone" : {
                "default" : "555-5555",
                "pattern" : "^[0-9]{3}-[0-9]{4}$",
                "type" : "string",
                "description" : "Any local phone number, no country or area code."
            },
            "boolean" : {
                "default" : true,
                "type" : "boolean",
                "description" : "Any boolean."
            },
            "integer" : {
                "default" : 7,
                "type" : "integer",
                "description" : "Any integer."
            },
            "string2" : {
                "default" : "Example 2",
                "minLength" : 2,
                "type" : "string",
                "description" : "Any string from 2 to 15 characters long.",
                "maxLength" : 15
            }
        }
```

Before a job is persisted to the database (in `Job.save()`), if config is `None` (or an empty dictionary*), create a config map using the `default` key listed for each key in the gear's config. If there is no default, do not add the config key.

**Comment by ryansanford** [comment]
@nagem What is the effort and risk to accomplish this? Something Ambrus or David could pick up?

**Comment by nagem** [comment]
Effort level is minimal, definitely something they could pick up. I'll assign it to them and add a bit more description.

**Comment by nagem** [comment]
@kofalt Should there be a way to create a job with intentionally blank config? Note the asterisk above. We could decide that empty dictionaries specifically mean no defaults should be applied.

**Comment by nagem** [comment]
I view assigning default config if there is none as a convenience rather than a business decision. Is there any situation where we wouldn't assign a config if the gear requests it and has defaults available? Would we just call the above method in every instance where a job is created? I'm not sure how I feel about that solution either.

**Comment by kofalt** [comment]
I lost a well-written reply due to laptops, but I want object modification to be explicit rather than implicit. Otherwise we have spooky action at a distance, which is bad. To answer your question: probably no, and probably yes.
