### ISSUE TITLE
SSE endpoints are not delivered correctly

### ISSUE THREAD

**Issue by kofalt** [scitran/core#946]
Dan and I observed a new bug in the SSE endpoint `/projects/x/packfile-end`. All responses are not delivered in real-time as they should be, and instead are buffered and delivered all at the end.

This causes two problems. One, the progress or other live events are not delivered to the user in a timely fashion, and two, the gateway will time out if the operation takes too long because no traffic is being sent.

You can observe this by adding `time.sleep(1)` to `PackfilePlacer.finalize`.

Ryan, my initial thought is this might be an gateway problem. Nginx response buffering?

**Comment by ryansanford** [comment]
@kofalt Which part of the stack is timing out, the web client (browser)?

Our nginx config has uwsgi buffering off, so that should not be a factor. Something simple to rule out TCP buffering as a cause would be to run with socket option `TCP_NODELAY`. I'll confirm how to do that with our docker environment and get back to you.

**Comment by ryansanford** [comment]
tcp_nodelay is already enabled with our nginx. Looking at uwsgi next...

**Comment by kofalt** [comment]
Nginx delivers a gateway timeout. You can trivially reproduce by adding `import time; time.sleep(1)` to [this line](https://github.com/scitran/core/blob/20a508d1c68fcf05588a2c5ce5340277d273660c/api/placer.py#L470-L475) and uploading a sufficiently large dicom set (mine happened with a series of ~250 dicoms).

**Comment by kofalt** [comment]
I'm not sure what changed, because this definitely used to work. Maybe we should diff our uwsgi / nginx configs from 6 months ago or so? Bisect? :slightly_smiling_face:

**Comment by ryansanford** [comment]
@kofalt I can reproduce issue fine. I've confirmed that SSE responses are not flowing out of uwsgi until all responses are available. This is after applying the tcp-nodelay flag to uwsgi.

Command I'm using to inspect that traffic... `docker run --rm --net=container:docker_uwsgi_1 crccheck/tcpdump -i any --immediate-mode -w - | wireshark -k -i -` 

Conclusion: Nginx is not the cause.

**Comment by kofalt** [comment]
Nice!

**Comment by kofalt** [comment]
Any update on this? The server will timeout large operations until this is fixed.

**Comment by ryansanford** [comment]
@ambrussimon To reproduce in flywheel development environment, and confirm incremental updates not sent from uwsgi...

1. Checkout the `repro-sse-issue branch`
2. Restart environment with `-r` flag
3. Start wireshark via `docker run --rm --net=container:docker_uwsgi_1 crccheck/tcpdump -i any --immediate-mode -w - | wireshark -k -i -`
4. `fw import <path-to-dir>` where <path-to-dir> is this zip extracted [sse-timeout.zip](https://github.com/scitran/core/files/1604265/sse-timeout.zip)
5. in Wireshark, use the filter `tcp contains "packfile-end"` display filter to catch the `packfile-end` request.
6. In wireshark, follow the TCP stream of that request found using the filter

This demonstrates that uwsgi is not transmitting those SSE messages back real time.

Remove all but file of the dicom files in the extracted zip to see what they should look like, though they still are not individually delivered.
