### ISSUE TITLE
Downloading (all) Analysis results delivers empty archive

### ISSUE THREAD

**Issue by dpuccetti** [scitran/core#949]
Example ticket request / response:

GET `/api/sessions/57c822ee4de7e6786671b62c/analyses/5980c4ca062ce4001ed74a1a/files?ticket=`

Response:
`{"ticket": "37001c25-fcc4-499a-8ccb-d2a3dc8e5b7b", "filename": "analysis_lda-insp 08012017 131326.tar", "file_cnt": 1, "size": 664601}`

The file downloaded with the ticket is sent with the correct filename, but is empty.

**Comment by nagem** [comment]
Fixed via #951
