### ISSUE TITLE
Move file types to mongo container, use regex for matching

### ISSUE THREAD

**Issue by nagem** [scitran/core#955]
For all files that are added to the system without the user specifying a type, the API attempts to assign the file a type using the extension. Currently, this mapping of extension -> type is hardcoded in the source code here: https://github.com/scitran/core/blob/master/api/filetypes.json. This is no longer sustainable for a few reasons: 
 
  - Changes/additions are tied to releases of core
  - Extensions alone are not enough to properly type files (ex. efile and pfile have the same extension but can be differentiated by beginning with "E" or "P")
  - All sites must use the same mapping

**Proposal:** 
  - [x] Add new mongo collection `filetypes` that stores the file type as the `_id` and a regular expression that matches on files that should be 
  - [x] Add API endpoints that would support clients adding/replacing and removing file types
     - Since these are simple key-value, modifying functionality seems overkill, a singular insert or replace endpoint probably fine. 
  - [x] Update util method to use new file type matching 
  - [x] Remove `filetypes.json`, convert existing mappings to objects that can be inserted into mongo
as defaults

**Concerns:** 
  - If a filename matches multiple types, we might want to think about ordering the types by precedence

**Comment by nagem** [comment]
Above is just a proposal, feel free to implement as you see fit while keeping the requirements in mind.

**Comment by kofalt** [comment]
I would suggest layering, such that for every key not present in the `filetypes` collection we fall back on `filetypes.json`. That was it's not an ops problem.

Otherwise :+1:

**Comment by nagem** [comment]
The plan is to move the existing filetypes.json into an ops role where it is loaded as default. The current json file will be removed from core.

**Comment by kofalt** [comment]
That's what I was proposing against, but if everyone wants that instead lets go for it :)
