### ISSUE TITLE
Mark files created via a job that fails

### ISSUE THREAD

**Issue by nagem** [scitran/core#968]
We need to clearly distinguish outputs of a failed gear from those of a succeeded gear. Even outputs from a "failed" gear may be valuable or even valid. Without them, debugging would likely be impeded, if not impossible.

Analysis gears
  - Analyses are directly tied to a job, so marking output files might be redundant

Utility Gears
  - For failed utility gears, output files will be added to acquisitions us usual, but those files will be marked in the DB
  - no gear rules will fire on those files until they are accepted (or deleted) by a user

Remaining questions
  - Metadata from failed gears should be handled in a similar fashion, but details TBD.

**Comment by kofalt** [comment]
> marked in the DB

Is the origin an insufficient mark?

**Comment by nagem** [comment]
@kofalt the origin would need to get modified to mention the job failed, but it could be stored in the origin. It would need to be something that doesn't have to get cross referenced for efficient querying.

**Comment by nagem** [comment]
Would a user either accept all the outputs or none of the outputs? If so, this gets a little easier. After a user chooses to accept the results of a failed job, all files could be updated and the metadata applied.

**Comment by kofalt** [comment]
If the motivation is for efficiency, let's keep it out of the origin object, since there can be very different sorts of origins. I'm not sure about accepting all / none / some, my guess would be all of the above.

**Comment by nagem** [comment]
Asking @gsfr, a user would either accept all or none of the changes. If all, the metadata will be applied following the some code paths as the engine upload endpoint and the files will be unmarked. If not accepted, the files with the unaccepted failed job as their origin will be removed.

**Comment by kofalt** [comment]
That seems straightforward.

How about a `from_failed_job: bool` or similar key on the file then?

**Comment by gsfr** [comment]
@nagem That's right. Let's start with all or nothing. But let's also keep in mind that future customer demand may require further refinement. No action item. Just food for thought.

**Comment by kofalt** [comment]
API design from out of band:

> I would have a PrepareComplete endpoint on something like `/jobs/x/prepare-complete`
> 
> And that is called first, with a blob of json - for now, probably just a success bool. More to add later. Returns `{ "ticket": "aex" }`
> 
> The engine calls that first, and waits for any log adds to complete.
> 
> Then calls Complete on `/jobs/x/complete?ticket=XYZ` - and that's with all the files.
> 
> That endpoint can use an engine placer, and will have the ticket ID to use.
>
> So basically the same endpoints as before, but more explicitly engine-related and more thoughtful
> 
> And now, the placer can incrementally process files while still knowing job results ahead of time.

This design would obsolete #941.

**Comment by kofalt** [comment]
Because the above design constitutes a breaking change for the engine, I've decided that we must leave the old routes in place so that the engines can survive an upgrade.

1. The old routes & logic will stay in place, with the exact same old behavior. 
1. New routes & new placer, with enhanced behavior.
1. Engine is upgraded to use new routes.
1. Old routes are removed in a subsequent release.
