### ISSUE TITLE
Python filenames must be unique

### ISSUE THREAD

**Issue by kofalt** [scitran/core#977]
Our log format mentions a filename:

```
2017-10-31 20:48:18      scitran.api                  base.py   191:DEBU None
```

Unfortunately, we have a `dao/base.py` and a `web/base.py`. Might be others.

**Comment by nagem** [comment]
I'm not sure making all filenames unique is the only solution we have. There aren't many overlaps and the overlaps are between two files, so line number can be use to distinguish when investigating log messages. We can probably update the logger to include package name as well.

**Comment by kofalt** [comment]
I mean, sure, but looking up line 191 in one file to see if there's a `log.whatever` is a little silly, right? Adding the package would work too, but seems like a waste of scarce log line characters... I'm down to either add the package logging or just rename a file.

**Comment by nagem** [comment]
I consider it silly to require file name uniqueness across a growing code base. Even if we fix the files we have control over, there will always be `__init__.py` conflicts. Common names like `base` and `handlers` are expected if we separate our project into packages/modules.

**Comment by kofalt** [comment]
¯\\_(ツ)_/¯ Whatever works! Think of all the fun adventures into a thesaurus we could have...
