### ISSUE TITLE
Disallow empty uploads

### ISSUE THREAD

**Issue by gsfr** [scitran/core#993]
Allowing file-less uploads on reaper-focussed endpoints (`/upload/uid`, `/upload/label`, `/upload/reaper`) is unintended and needlessly complicates debugging of reaper tools. I suggest we stop allowing such *empty* uploads.

**Comment by gsfr** [comment]
This may also affect the CLI's import functionality. cc @kofalt

**Comment by kofalt** [comment]
Does "empty" mean "no files but some metadata"? Or "literally nothing useful."

I don't think the CLI currently does either of those things.

**Comment by gsfr** [comment]
Thanks, @kofalt. I meant "no files, but metadata". And the reaper was doing that by mistake.

And thanks, @hkethi002.
